- etc/wpantund.rb
Without this change, attempting to do a `brew install` fails with the following error:
Error: Version value must be a string; got a NilClass
> brew: The `devel` section needs a version to work

- configure.ac
- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/util/SuperSocket.cpp
- src/util/SuperSocket.h
- src/util/socket-utils.c
- src/util/socket-utils.h
Addresses issue #7.
Added some rudimentary PID to FD tracking so that when we close a file
descriptor opened by `open_serial_socket()`, the process behind that socket
(if any) is explicitly terminated.
This unfortunately requires us to add a new function called
`close_serial_socket()`, but in this particular case the change was not
onerous.
We are only handling five such sockets for now. If there are ever more than
that many system sockets opened through this mechanism, then something is
likely seriously wrong.
The socket tracking code is super simple and possibly not thread safe,
which is fine in this case since these methods will only ever be called
from the same thread.
I really wish these sorts of antics were not necessary, but all other
methods of handling this sort of thing seem to …
> socket-utils: Ensure child processes are terminated upon socket close

- configure.ac
- src/wpantund/wpantund.cpp
The `wpantund` main loop detects cases of excessive thrashing
(which is almost always a bug) and prints out a log message
indicating that the thrashing is taking place. This change
also prints out the current load average on systems where it
is available.
> wpantund: Show load average when main loop is thrashing.

- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
This change adds a return value of type `wpantund_status_t` to `NCPInstanceBase::set_ncp_version_string()`. If the new version string does not match the previous value, the function will invoke `ncp_is_misbehaving()` to reinit the NCP and it will return `kWPANTUNDStatus_InvalidArgument`. Otherwise a success status of `kWPANTUNDStatus_Ok` is returned.
> NCPInstanceBase: Add return status to set_ncp_version_string()

- src/wpantund/NetworkInstance.h
Missing code for big endian systems.
As a side remark, it is sometimes unclear where should little/big/host values be used. I think it would be better (more compact and clearer to the reader) to use htole/htobe functions in the future, rather than the custom memcpy based on a define. Also we should check, maybe even add a test, to check spinel compatibility when different endianess architectures are communicating.
> Fix xpanid set/get methods on big endian systems

- src/ncp-spinel/SpinelNCPInstance.cpp
- third_party/openthread/src/ncp/spinel.h
This commit adds support for Spinel counters, which are being tracked on the OpenThread project by issue [openthread/openthread/199][1].
[1]: https://github.com/openthread/openthread/issues/199
> ncp-spinel: Add support for Spinel counters.

- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
This change was deemed necessary because we saw a case where a
device entered the `OFFLINE` state from the `UPGRADING` state, 
which caused all sorts of havoc.
This change adds some additional checks when a state transition
is triggered so that we detect and report invalid state transitions.
In some cases, invalid state transitions are actually outright
prevented, such as transitioning directly from a detached state
(like `FAULT` or `UPGRADING`) to any state other than `UNINITIALIZED`.
All invalid state transitions are clearly indicated to be bugs
in the logs.
> NCPInstanceBase: Detect and report invalid state transitions

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/wpanctl/tool-cmd-scan.c
- src/wpanctl/wpanctl-utils.c
- src/wpanctl/wpanctl-utils.h
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPTypes.h
This commit makes the following changes:
- New methods are introduced in `NCPControlInterface` class for
starting or stopping energy scan.
- It adds new dbus APIs for requesting energy scan and signaling
the scan results (DBus APIs v1).
- The wpanctl scan command is modified to enable both network
scan and energy scan, and to be able to parse and output the
energy scan results.
This commit does not add the implementation of energy scan for
Spinel plugin.
> Adding support for `energy scan` to core wpantund and wpanctl.

- src/ncp-spinel/Makefile.am
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPTaskChangeNetData.cpp
- src/ncp-spinel/SpinelNCPTaskChangeNetData.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit changes how the `config_gateway`, `add/remove_external_route` are implemented in `SpinelNCPControlInterface` (spinel plugin). It ensures that after an update to any local network data (mesh prefixes or external routes), the new data is registered with the leader. This is done by adding a new Spinel property `THREAD_ALLOW_LOCAL_NET_DATA_CHANGE` with boolean type. This property is set to 'true' before modifying any properties related to local network data. When done, this property is set to 'false' causing the network data to be registered with leader. This commit also adds a new SpinelNCPTask, namely `SpinelNCPTaskChangeNetData` which implements the common logic for changing any net data property.
This commit is related to openthread issue #272.
> SpinelNCPControlInterface: Fix config_gateway, add/remove external route

- src/connman-plugin/wpan-connman-plugin.c
This commit changes the wpan-connman plugin so that when NCP state changes to `associated` state, plugin removes all the other networks (services) from the lowpan device.
> wpan-connman-plugin: Remove scanned networks upon a successful connect

- src/connman-plugin/wpan-connman-plugin.c
This commit changes how the disconnect is handled in the wpan-connman-plugin. If a disconnect command/call is received and if this is not user initiated, the current NCP state is checked:
If it is in `ASSOCIATING` or `NCP_STATE_CREDENTIALS_NEEDED` states, instead of issuing a `Leave` command to wpantund, we `Reset` the NCP. This ensures that ongoing association process is stopped, but will not remove/erase any retained NCP network info.
> wpan-connman-plugin: Ensure that network info is retained in case of Connman untimely restart 

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
This commit fixes a copy-paste bug that accidentally fetched
counter values as 8-bit values, when they are actually 32-bit values.
This caused only the least-significant portion of the counter
to be returned.
At initialization, we have a list of properties we want to
try and fetch so that we can make sure that the state in
`wpantund` matches that of the NCP. However, not all of these
properties might be implemented, which is OK. In such a case
we log a warning and continue.
The wording of this error message has caused some concern, so
I've reworded the error message and also change the warning
to also lookup the textual representation of both the property
and the error, so that it is clear what exactly happened.
It was noticed that when wpantund entered the `uninitialized:fault`
state …
> ncp_spinel: Miscellaneous minor bug fixes

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/NCPConstants.h
Instead of writing log messages directly to the serial port, Spinel
has the capability to allow the NCP to write its log messages directly
to the host in-band via the Spinel stream property
`PROP_STREAM_DEBUG`.
This change makes sure that any log messages written to
`PROP_STREAM_DEBUG` get written to the `wpantund` logs.
> ncp_spinel: Log data from PROP_STREAM_DEBUG to SysLog

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/util/sec-random.c
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
Forgot to set up some code for getting all of the non-config
settings working properly, like `Daemon:AutoFirmwareUpdate`.
> ncp_spinel: Fix for setting non-config properties in configuration file

- src/scripts/wpanretain.sh
- src/wpantund/Makefile.am
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/NetworkRetain.cpp
- src/wpantund/NetworkRetain.h
- src/wpantund/wpan-properties.h
This commit adds a new class `NetworkRetain` to wpantund. This class provides hooks to enable retaining (saving/recalling) network info. This is realized by adding a new configuration property to wpantund `Config:Daemon:NetworkRetainCommand`. This property provides the command to perform the network retain operations. The `NetworkRetain` class executes the retain command from a forked child process to request  a save operation (when NCP state transition to "associated" ) or an erase (upon a `leave`) or network info recall and restore (upon NCP reset or a wpantund restart). The `NetworkRetain` uses the same model as in `FirmwareUpgrade` module (i.e., the forked process
is started before wpatund possibly dropping privileges).
This commit also adds a script `wpanretain.sh` which can be used …
> Adding NetworkRetain class and wpanretain script

- src/wpantund/NCPInstanceBase.cpp
This fixes a bug where `wpantund` terminates after a firmware update
with the error `select() errno="Bad file descriptor" (9)`.
> NCPInstanceBase: Reset data pump NLPTs when entering a detached state

- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/NCPInstanceBase.cpp
If this isn't allowed, we might never be able to query the NCP for status if it enters the FAULT state.
This pull request also include the following commit:
* ncp: Stop printing out `get_property` debug prints during initialization.
During initialization, logs were being polluted with lines like:
wpantund[12345] <info> get_property: key: "NCP:State"
wpantund[12345] <info> get_property: key: "NCP:State"
wpantund[12345] <info> get_property: key: "NCP:State"
These lines are useless, and come from the the main wpantund run-loop
attempting to determine if the NCP instance is ready to be announced
via D-Bus. However, this log line is still generally useful, this
commit adjusts the behavior to only print this message when we are not
initializing.
> NCPInstanceBase: Allow FAULT and UPGRADING states to be reported, even when initializing.

- src/scripts/wpanretain.sh
This commit changes the `wpanretain.sh` script to make in more compatible with different bash scripts. Also fixes some issues with parsing/setting of the network-name and xpanid.
> Update the wpanreatin.sh script (increase compatibility)

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- src/ncp-spinel/SpinelNCPTaskLeave.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This change is required to have `wpantund` successfully control
OpenThread NCPs after [OpenThread pull request #372][1] is merged
in.
Versions of `wpantund` that include this change *should* be able to
continue to control older NCPs, but no guarantees are made.
[1]: https://github.com/openthread/openthread/pull/372
> ncp-spinel: Updates to Spinel API from OpenThread.

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskChangeNetData.cpp
- src/ncp-spinel/SpinelNCPTaskChangeNetData.h
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- third_party/openthread/src/ncp/spinel.h
* ncp-spinel: Handle adding and removing of unicast addresses.
* ncp-spinel: Don't clear addresses when we get a new IPv6 address table.
* ncp-spinel: Allow the channel to be set for join.
> ncp-spinel: Miscellaneous bug fixes

- src/ipc-dbus/DBUSIPCServer.cpp
- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/wpantund/Makefile.am
- src/wpantund/NCPMfgInterface_v0.h
- src/wpantund/NCPMfgInterface_v1.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
- Spinel: add 'SPINEL_PROP_NEST_STREAM_MFG' property
- D-Bus: add 'WPANTUND_IF_CMD_MFG' command
- Move original 'NCPMfgInterface' to 'NCPMfgInterface_v0', add new 'NCPMfgInterface_v1'
> Add diagnostics(mfg) interface in wpantund

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/NCPTypes.cpp
- src/wpantund/NCPTypes.h
- third_party/openthread/src/ncp/spinel.h
This commit makes sure that wpantund adds the appropriate addresses to the interface as on-mesh prefixes become available.
> ncp-spinel: Add addresses for on-mesh SLAAC prefixes.

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit adds support to wpantund for newly added NCP counters which track number of events/messages through the NCP (e.g., number of IP packets sent/received (secure vs insecure), number of dropped IP packets, number of spinel frames, etc.
> SpinelNcpInstance: Add support for newly added NCP counters.

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/util/IPv6Helpers.cpp
- src/util/IPv6Helpers.h
- src/util/Makefile.am
- src/util/TunnelIPv6Interface.cpp
- src/util/TunnelIPv6Interface.h
- src/util/tunnel.c
- src/util/tunnel.h
- src/wpantund/Makefile.am
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase-NetInterface.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
`wpantund` has traditionally treated the link local address and the
mesh-local/realm-local addresses as special and handled them independently
from other addresses. I now believe this was a mistake.
This change unifies how all addresses are handled into one single list
that addresses get added to and removed from. This approach simplifies
the internal API and also makes general address housekeeping much easier.
This is a fairly invasive change, so extra care should be taken
in its review.
> wpantund: Refactor how the address list is handled.

- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTask.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- src/ncp-spinel/SpinelNCPTaskSendCommand.h
- src/wpantund/StatCollector.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
- wpantund.xcodeproj/project.pbxproj
This commit adds support for in-band assisted joining. This capability
allows a node (which does not yet have network credentials) to communicate
in a very limited fashion (a single application-defined port using IPv6
link-local addresses) with an "assisting device" (Joinable bit set).
Using an undefined application protocol, the joining device can learn the
network credentials from the assisting device and then proceed to join the
network normally.
This change relies on the changes from [OpenThread Pull Request #497][1].
[1]: https://github.com/openthread/openthread/pull/497
> ncp-spinel: Add support for in-band assisted joining

- src/wpantund/NCPTypes.cpp
This commit enhances the `string_to_node_type()` to allow some more commonly used strings to be used as node type (e.g., "sed" or "sleepy" for sleepy-end-device).
> NcpTypes: Enable conversion of new "node type" strings.

- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support to `SpinelNCPTaskJoin` to enable joining as an `end-device`. It uses the newly added spinel property `SPINEL_PROP_THREAD_ROUTER_ROLE_ENABLED`.
This relies on the changes in openthread PR [523](https://github.com/openthread/openthread/pull/553)
> SpinelTaskJoin: Add support for joining as an end-devcie

- src/util/args.h
- src/wpanctl/tool-cmd-form.c
- src/wpanctl/tool-cmd-join.c
- src/wpanctl/wpanctl-utils.c
- src/wpanctl/wpanctl-utils.h
This commits adds to output of `wpanctl` `join` and `form` commands to inlcude the `node-type`. It also modifies the `arg.h` to include the arg type in the printout and adds info in help for valid node types.
> wpanctl: Print node-type in `join`/`form` commands

- src/ncp-spinel/Makefile.am
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskGetChildTable.cpp
- src/ncp-spinel/SpinelNCPTaskGetChildTable.h
- src/wpantund/wpan-properties.h
This commit adds support to spinel plugin for getting the child table property `SPINEL_PROP_THREAD_CHILD_TABLE`. It also adds a new read-only wpantund property `Thread:ChildTable` to retrieve the child table along with info about each child.
This is the counterpart of the openthread PR [#515](https://github.com/openthread/openthread/pull/515).
> Adding support for getting child table

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPTaskScan.cpp
- src/ncp-spinel/SpinelNCPTaskScan.h
- third_party/openthread/src/ncp/spinel.c
This commit adds support to spinel plugin for energy scan operation, specifically it modifies the `SpinelNCPTaskScan` to handle both netscan (active scan) and energy scan operations.
The counterpart of this change in openthread is in [PR580](https://github.com/openthread/openthread/pull/580).
> Add support for Energy Scan operation in Spinel plugin

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskLeave.cpp
This pull request contains two changes:
* ncp-spinel: Allow leave command to work even while NCP is initializing.
* ncp-spinel: Remove obsolete start_new_task() design pattern
> Fixes for miscellaneous bugs

- src/ncp-spinel/SpinelNCPControlInterface.cpp
This commit changes the `SpinelNCPControlInterface::config_gateway` implementation so that when an `ON_MESH_PREFIX` is added the stable flag is set to `true` by default.
> Add ON_MESH_NETs and LOCAL_ROUTs with stable flag set to true

- src/wpantund/NCPInstanceBase-NetInterface.cpp
Upon leaving a network, we were not clearing `wpantund`'s global address
table. This would cause these old addresses to be re-added to the interface
when the same instance of `wpantund` associated with a new network.
This change fixes this issue by making sure that we clear the global
address table whenever we reset the interface.
> NCPInstanceBase: Make sure we clear the global address table upon reset

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit changes the `SpinelNCPInstance::address_was_added()` so that when an `ON_MESH_PREFIX` added the stable flag is set to `true`.
> Ensure stable flag is true for on-mesh-prefix added from `address_was_added()`

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpanctl/Makefile.am
- src/wpanctl/tool-cmd-pcap.c
- src/wpanctl/tool-cmd-pcap.h
- src/wpanctl/wpanctl-cmds.h
- src/wpanctl/wpanctl-utils.h
- src/wpantund/Makefile.am
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPInstanceBase-AsyncIO.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/Pcap.cpp
- src/wpantund/Pcap.h
- src/wpantund/wpantund.cpp
This pull request adds support for the capture and logging of raw packets from the radio, assuming the underlying NCP supports it.
Note that this feature captures raw packets from the radio, which will currently always be 802.15.4 frames (but that may not always be the case in the future). If you just want to sniff IP traffic, you can simply use Wireshark or tcpdump directly.
Packets are captured in the PCAP format, which is the same format used by Wireshark and tcpdump. You can start a packet capture using the `pcap` command in `wpanctl`:
Syntax:
pcap [args] <capture-file>
Options:
-h/--help                 Print Help
-t/--timeout              Set timeout period [ms]
-f                        Force use of stdout, even if it is a tty
If you to not specify a file, `stdout` is used. If …
> wpantund: Support for raw packet capture (Packet sniffing)

- .travis.yml
- .travis/before_install.sh
This issue is tracking the fix for the recent onset of travis failures when building for OS X.
> Fix for sudden onset of travis OS X failures

- src/wpantund/NCPInstanceBase-NetInterface.cpp
- src/wpantund/NCPInstanceBase.cpp
This change adjusts the state change logic to ensure that
the global address table is only forcably cleared when we
have entered the offline state.
> NCPInstanceBase: Fix for dissapearing addresses after NCP crash

- src/wpantund/NCPInstanceBase.cpp
This commit changes the `NCPInstanceBase::is_busy()` to ensure that it returns `true` while NCP is being initialized.
> NCPInstanceBase: Don't allow host sleep while NCP is being initialized

- src/wpantund/StatCollector.cpp
This commit disables default 10 min periodic link-stat queries.
> StatCollector: Disable default periodic link-stat queries

- third_party/openthread/src/ncp/spinel.h
This syncs `spinel.h` with openthread at commit (#716) d1c83d3625
> Spinel.h: Sync spinel header file with openthread

- src/ncp-spinel/SpinelNCPInstance.cpp
- third_party/openthread/src/ncp/spinel.h
This is the `wpantund` update for the changes from [pull request #717][1].
[1]: (https://github.com/openthread/openthread/pull/717)
> ncp-spinel: Update raw stream to support new metadata format

- src/wpanctl/tool-cmd-setprop.c
This commit changes how the  wpanctl `setprop` command processes the options. The `-d` or `--data` can be used either before the property name or before the property value. This commit also removes the unused `-i` option.
> Update how `wpanctl setprop` processes  option arguments

- src/ncp-spinel/SpinelNCPInstance.cpp
- third_party/openthread/src/ncp/spinel.h
OpenThread Issue [#809][1] addresses some issues with the `PROP_STREAM_RAW` interface. This is the `wpantund`-side of those changes.
[1]: https://github.com/openthread/openthread/pull/809
> ncp-spinel: Updates for pcap support

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- src/wpantund/NCPInstanceBase-AsyncIO.cpp
- src/wpantund/Pcap.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This change allows the `wpanctl pcap` command to work when in an `offline` state. When started while `offline`, it puts the NCP into a promiscuous sniffing mode.
If you subsequently associate with a network while sniffing promiscuously, promiscuous mode is turned off and behavior reverts to the same as if you had started `wpanctl pcap` while associated.
This change also restores packet capture state properly after a NCP reset.
This pull request also includes the following other changes:
* 36d2dbf: Fix for incorrectly calculating time for next event
* 5547790: ncp-spinel: Join: Allow `ALREADY` error when setting `PROP_NET_IF_UP`
> ncp-spinel: Add support for promiscuous packet capture

- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/util/IPv6Helpers.h
- src/wpanctl/tool-cmd-config-gateway.c
- src/wpanctl/tool-cmd-pcap.c
- src/wpanctl/tool-cmd-reset.c
- src/wpanctl/tool-cmd-resume.c
- src/wpanctl/tool-cmd-scan.c
- src/wpanctl/tool-cmd-setprop.c
- src/wpanctl/tool-cmd-status.c
- src/wpanctl/wpanctl-utils.c
- src/wpantund/NCPControlInterface.h
- src/wpantund/wpan-error.h
As a carry-over from days long gone, several code paths in `wpantund` measure the prefix length in bytes, not bits. This change addresses this issue.
Also includes improvements for a common error condition (interface not found) in `wpanctl`.
> Measure prefix length in bits, not bytes

- src/wpanctl/tool-cmd-pcap.c
This change clarifies the `--help` documentation and also improves the detection of possibly accidental packet capture to a controlling TTY.
> wpanctl: pcap: Improve the pcap command to be less confusing.

- configure.ac
- src/ncp-spinel/Makefile.am
- third_party/openthread/tools/spi-hdlc-adapter/.gitignore
- third_party/openthread/tools/spi-hdlc-adapter/README.md
- third_party/openthread/tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This change makes OpenThread's `spi-hdlc-adapter` build and install when building and installing the `nap-spinel` plugin. This makes it easier to get up and running on SPI-based platforms without needing to deal with building OpenThread.
Since `spi-hdlc-adapter` is a Linux-only tool, it is only built when the host platform is Linux.
> third_party/openthread: Include building spi-hdlc-adapter for convenience

- src/wpantund/NetworkInstance.h
- src/wpantund/StatCollector.cpp
- src/wpantund/StatCollector.h
This commit makes two changes:
- `StatCollector` registers to receive the NetScan results and prints
the scan result info (network name, panid, xpaindi, etc.) to syslog.
- A `version` field is added to `NetworkInstance` struct.
> StatCollector: Add scan result info to the logs

- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This PR adds the following 
- Support for passing the legacy prefix during "form" operation.
- Adds new legacy related spinel properties.
> Adding support for legacy network to spinel code

- src/scripts/wpanretain.sh
This commit fixes an issue with wpanretain script where the `routerid` was caluclated incorrectly. It also fixes style to use tabs.
> wpanretain.sh: Fix the retain script to use the cur_routerid

- src/wpanctl/tool-cmd-getprop.c
Reset optind to 0 in tool_cmd_getprop. 
Without this zeroing, when getprop is used with the --all or -a options, it will end up in infinite recursion.  This is because the value of optind is persistent across function calls, and since getprop --all results in an optind of 2 and the recursive calls of getprop {property} will always have an argc of 2, optind == argc will be true, causing every recursive call to be treated like a new call to getprop --all.
> wpanctl getprop --all infinite recursion

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskGetChildTable.cpp
- src/ncp-spinel/SpinelNCPTaskGetChildTable.h
This commit changes the `TaskGetChildTable` to expose some new methods (to parse/get the child table from the corresponding spinel message). It also adds logs
- when `LAST_STATUS` is received (the status)
- when `CHILD_TABLE` property changes is received (prints the entire
child table in the syslogs).
> Add child table and last status logs

- src/wpanctl/tool-cmd-mfg.c
The output from this command was previously a little janky and hard to parse. This commit fixes it.
> wpanctl: Clean up the output of the `mfg` command.

- src/ncp-spinel/SpinelNCPInstance.cpp
This PR changes the `handle_ncp_spinel_value_is()` in `SpinelNcpInstance` to save a copy of original spinel `data_ptr` and `dat_len` (before parsing the spinel message). The saved copy of `data_ptr` and `data_len` is then passed at the end to any event-handler in `process_event()` call.
> Ensure the event-handler gets the original spinel data message

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
This commit adds support in `SpinelNcpInstance` to save and restore certain settings/properties. This is currently used to remember the jamming detection related parameters.
The settings are stored in a hash table which maps the property name (as `std::string`) to a `SettingsEntry` struct.  The `SettingsEntry` contains the spinel command to set the value of the property, along with an optional capability value. At the end of NCP initialization, if the `capability` value is given and it is present in the list of NCP capabilities, the associated spinel command is sent to NCP to set/restore the value of the the property.
> Add support to save and restore certain radio properties during initialization

- src/ncp-spinel/SpinelNCPTaskSendCommand.cpp
- src/ncp-spinel/SpinelNCPTaskSendCommand.h
This commit modifies the `SpinelNCPTaskSendCommand` to add support for handling user-specified reply formats.
The `Factory` class currently allows the caller to provide a simple single type spinel reply format. This commit adds support in this class to alternatively specify a `ReplyUnpacker` function pointer. When specified, the `ReplyUnpacker` function is invoked to unpack/decode the reply message.
> NCPTaskSendCommand: Add support for `ReplyUnpacker` function pointer

- src/wpanctl/wpanctl.c
- src/wpantund/FirmwareUpgrade.cpp
- src/wpantund/NetworkRetain.cpp
In a handful of places, `stdin` and `stdout` were being used as l-values. While `stdin` and `stdout` can be used as an l-value in many standard library implementations, it is explicitly stated in C89 that it is acceptable for implementations to not make these symbols l-values. Issue #89 is an example of this.
This change rewrites all places where we are using these variables as l-values so that `wpantund` can be used on those platforms.
This commit fixes and closes #89.
> Do not use stdin or stdout as an l-value

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds a new wpan property to get the jam detection history bitmap. This value provides information about current state of jamming detection module for monitoring/debugging purpose. It returns a 64-bit value where each bit corresponds to one second interval starting with bit 0 for the most recent interval and bit 63 for the oldest intervals (63 sec earlier). The bit is set to 1 if the jamming detection module observed/detected high signal level during the corresponding one second interval.
(This commit also fixes some of the indention in `SpinelNCPInstance.cpp` to use tabs everywhere). 
The counter-part of this change in OpenThread: https://github.com/openthread/openthread/pull/1033
> Add support for new property "JamDetection:Debug:HistoryBitmap"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/NCPInstanceBase-NetInterface.cpp
This commit makes the following changes:
- In `NCPInstanceBase::set_online()` new code is added to add mesh-local address (in non-zero) when the interface is brought online. This helps address an issue where the mesh-local address was not added after a reset.
- In `SpinelNCPInstance::handle_ncp_spinel_value_is()` when processing the receiving of new mesh-local address, the codechecks that the old value of `mNCPMeshLocalAddress` to ensure it is non-zero before trying to remove it (this helps remove an unnecessary `require` failure message from the logs).
> NCPInstanceBase-NetInterface: Add mesh-local address (if non-zero) in `set_online()`

- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- src/ncp-spinel/SpinelNCPTaskLeave.cpp
This commit changes the code to issue a spinel `CMD_NET_CLEAR`command before "form", "join" or after "leave" operations (in their corresponding `SpinelNCTTask`s) . This ensures that any saved network settings are erased.
https://github.com/openthread/openthread/pull/1123 is the counterpart of this change in OpenThread
> Erase saved network info before `form`, `join` and after `leave`

- src/ncp-spinel/SpinelNCPInstance.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commits contains the following changes:L
- A new check is added in `handle_ncp_spinel_value_is()` for
handling `NET_ROLE` changes to `DETACHED`. When a `DETACHED`
role change is received, and the state was previously in
associated state, the NCP state is updated to `ISOLATED`.
This addresses the case  where an end-device looses its parent
after a successful join.
- A new `LOG_INFO` level message is added to print the value of
`NET_ROLE` upon receiving it from NCP.
- It adds a new function in `spinel` to convert net_role values
to C strings.
> Change to `ISOLATED` state upon receiving `NET_ROLE_DETACHED` event from NCP

- src/ncp-spinel/SpinelNCPTask.cpp
The do-while loop in SpinelPackData would never run for a second time due to the fact it was a while(false), instead of a while(true)
> Fix loop in SpinelPackData

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
This commit changes the "Tickle" logic, so that it happens at certain intervals independent of us getting events from the NCP. This can help with cases where the Tx path may have an issue.
> Modify the "Tickle" logic

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
This commit adds a recovery mechanism for the case where we get back-to-back NOMEM status from NCP so that after some number (set to 15) of NOMEM status the NCP is reset.
This should help address possible memory leak or issues where radio may be getting stuck.
> Recovery mechanism for back-to-back NOMEM status from NCP

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/wpantund/NCPInstanceBase.h
- It parses the `SPINEL_PROP_PHY_CHAN_SUPPORTED` message and stores a set of supported channels.
- It adds new methods to get default channel mask.
- It modifies the `FormTask` to use the default channel mask if none   is given and ensures the selected channel is supported by NCP.
> Add supported channels set and use it during `form` if none is given

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
- Adds two new properties to wpantund "Thread:LeaderNetworkData" and
"Thread:StableLeaderNetworkData" to get the full/stable leader
network data from the NCP.
- Adds corresponding spinel properties `THREAD_LEADER_NETWORK_DATA`
and `THREAD_STABLE_LEADER_NETWORK_DATA`.
- In `handle_ncp_spinel_value_is()` we now print the leader network
data in the logs whenever we get an event from NCP notifying us of
a change in network data.
> Add new properties to get leader network data

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskSendCommand.cpp
This commit adds a callback in `address_was_added()` when issuing
the set the spinel commands to check for timeout error of the whole
operation.
> Check for time out error when adding address/on-mesh-prefix

- src/ncp-spinel/SpinelNCPInstance.cpp
- third_party/openthread/src/ncp/spinel.h
- Adds support for newly added counter in OpenThread to track
number of frame transmission failures due to abort error.
> Add support for new MAC counter `TX_ERR_ABORT`

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- It implements support for getting wpan property
"Network:IsCommissioned"  through the spinel property
`SPINEL_PROP_NET_SAVED`.
- It implements `vprocess_resume()` proto-thread to enable
auto-resume functionality:
If AutoResume (or "Daemon:AutoAssociateAfterReset") property
is `true`, then after NCP reset and its successful
initialization, if the NCP is commissioned, wpantund "resume"
with the saved network.
> SpinelNCPIntance: Enable auto-resume functionality

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTask.cpp
- src/ncp-spinel/SpinelNCPTaskLeave.cpp
This ensures that all the volatile memory on the NCP is wiped after
a network "leave" command.
> `TaskLeave`: Issue a "reset" at the end of "leave"

- third_party/boost/boost/smart_ptr/detail/sp_counted_base_sync.hpp
The header file is needed for cross-compiling with the toolchain:
* arm-linux-gnueabihf-gcc (Linaro GCC 5.2-2015.11-2) 5.2.1 20151005
It is copied from:
* https://sourceforge.net/projects/boost/files/boost/1.60.0
> Add a missed boost header file

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- src/ncp-spinel/SpinelNCPTaskLeave.cpp
One of the core cornerstones of Spinel is to not treat the failure of largely unrelated commands to be fatal. Currently, the absence of the net save commands is going to cause forming, joining, resuming, and leaving to fail. This is entirely unnecessary, since the failure of the net-clear command is not at all fatal.
> Make form/join/resume/leave less fragile.

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskScan.cpp
- src/ncp-spinel/spinel-extra.c
- third_party/openthread/README.google
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
- third_party/openthread/tools/spi-hdlc-adapter/README.md
- third_party/openthread/tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This pull request includes two changes, one is the sync of files that have changed in OpenThread and the other updates various parts of the Spinel plug-in to reflect those changes.
The later commit is larger than expected due to the realization that `spinel-extra.c` was quite crufty. The code in question wasn't being used in the ways in which it was broken, which is why we haven't seen any problems so far. Nonetheless, it seemed prudent to fix the code.
This change also includes the latest updates ([#1441](https://github.com/openthread/openthread/pull/1441)) to `spi-hdlc-adapter`, previous versions of which had a nasty frame corruption bug.
> Sync OpenThread files to latest versions and update plugin to match

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- Add a new wpan property "OpenThread:Debug:TestAssert" which maps
to `SPINEL_PROP_DEBUG_TEST_ASSERT`.
- Reading/Getting this property will cause an assert on NCP.
This is intended for testing the assert functionality of
NCP. Assert should ideally cause the NCP to reset, but if this is
not supported a `false` boolean is returned in response.
> Add support for new property to test assert functionality on NCP

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support for getting/setting a new wpan property
"OpenThread:LogLevel" tied to `SPINEL_PROP_DEBUG_NCP_LOG_LEVEL`
property. This property can be used to control the OpenThread NCP
log level dynamically.
By including this property in the `mSettings` hash table, it is
ensured that the user-selected log-level persists over NCP resets.
> Support for dynamic control of OpenThread NCP log level.

- src/util/netif-mgmt.c
This should address https://github.com/openthread/openthread/issues/1536.
> `netif-mgmt`: Fix the check for `SIOGIFINDEX` in `netif_mgmt_get_ifindex()`.

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
This commit removes the recovery mechanism which was  added in commit
f7e06585db for detecting back-to-back NOMEM status from NCP and
resetting the NCP. This was added to safe-guard against possible memory
leaks in NCP. It's recommend to instead add such a safe-guard in NCP.
> Remove the mechanism to detect for back-to-back NOMEM status from NCP

- src/util/DBUSHelpers.cpp
Notably, this typo prevented setting XPANID as a 64-bit unsigned integer
instead of a byte array.
> Fix typo that prevented setting unsigned 64-bit properties

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This PR adds a property to access the PSKc of Thread network. All implementation detail follows the way for Network Master Key.
> Add property Network PSKc

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskForm.cpp
Setting PSKc relies on forming network with given XPANID. This PR fixes #138 .
> Form network based on existing PANID and XPANID

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskForm.cpp
This commits adds new flag `mXPANIDWasExplicitlySet` to track if the
XPANID is set explicitly after a NCP reset. This is then used to
ensure that a random xpanid is generated and used during "form"
opeation if non was set earlier.
This change addresses an issue where newly formed network always end
up using the default OpenThread XPANID value of `0xDEAD00BEEF00CAFE`.
> Ensure to user a random xpanid during "form" if none was set explicitly earlier

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
This commit adds new feature to allow setting of the steering data
when the joinability status gets changed (through `permit_join()`).
This feature requires the NCP `SPINEL_CAP_OOB_STEERING_DATA`
capability.
This commit defines two new wpan properties:
1) `OpenThread:SteeringData:SetWhenJoinable` (boolean) which defines
whether or not when the device is joinable the steering data is set.
The default setting is `false`. It is recommended that this property
is changed using `wpantund.conf` during initialization.
2) `OpenThread:SteeringData:Address` (eui64 value) which specifies the
address used to set the steering data (out of band) using the spinel
property `SPINEL_PROP_THREAD_STEERING_DATA` (the given eui64 is used
to compute the bloom filter which is used as the steering data).
Default …
> Add support for controlling steering data when joinable

- src/ncp-spinel/SpinelNCPInstance.cpp
This helps reduce the log clutter.
> Filter the "CMD_PROP_VALUE_IS(PROP_STREAM_DEBUG)" out from wpantund logs

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit updates the spinel source files from OpenThread at commit
https://github.com/openthread/openthread/commit/9c09577d528bcf89f0197a68b9db775915ebebfd. It also addresses a property name change:
- `THREAD_LOCAL_ROUTES` -> `THREAD_OFF_MESH_ROUTES`.
> Update `spinel.h` and `spinel.c` from OpenThread

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit adds new logs to show what capabilities the NCP is providing (e.g., during initialization when we get the `SPINEL_PROP_CAPS` property).  Helpful for debugging
> Log NCP capabilities when parsing `SPINEL_PROP_CAPS` response

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPTaskScan.cpp
- src/ncp-spinel/SpinelNCPTaskScan.h
- src/wpanctl/tool-cmd-scan.c
- src/wpantund/wpan-properties.h
This commit includes the following changes: It updates the `TaskScan`
implementation to add support for the discovery scan in addition
energy and network scan operations It also adds a new dbus method for
MLE discovery scan. The wpanctl "scan" command is  updated to add
options for the new discover scan ("scan -d" to start a discovery
scan).
> Add support for MLE discover scan

- bootstrap.sh
header of bootstrap.sh is
```sh
#!/bin/sh
```
However it uses feature `[[` which is of `bash` only. We can either change the header, to remove the dependency on `bash`. I think `sh` is more general. This PR simply removes the usage of `[[`.
> Make consistent of bash or sh in bootstrap.sh

- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
This commit changes the string representation of a child info. Note
that the keys used for value-map output remains unchanged. This
change helps with the issue where the log strings could be clipped
off from logs due to size limit of syslog.
> Shorten the child info string representation

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/NCPControlInterface.cpp
- src/wpantund/NCPControlInterface.h
- src/wpantund/wpan-properties.h
The wpan property is related to `SPINEL_PROP_THREAD_OFF_MESH_ROUTES`
property.
> Adding new wpan property "Thread:OffMeshRoutes" and its 'get' support

- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v0.h
- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v0.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpanctl/Makefile.am
- src/wpanctl/tool-cmd-insertprop.c
- src/wpanctl/tool-cmd-insertprop.h
- src/wpanctl/tool-cmd-removeprop.c
- src/wpanctl/tool-cmd-removeprop.h
- src/wpanctl/tool-updateprop.c
- src/wpanctl/tool-updateprop.h
- src/wpanctl/wpanctl-cmds.h
- src/wpantund/NCPControlInterface.cpp
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPInstanceBase-NetInterface.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/StatCollector.cpp
- src/wpantund/StatCollector.h
- src/wpantund/wpan-properties.h
- src/wpantund/wpantund.cpp
Spinel provides support for properties that are list-based. It also defines `VALUE_INSERT` and `VALUE_REMOVE` to insert or remove an element into a list-based property. This turned out to be a very useful model. This PR aims to provide base support for similar functionality in wpantund. 
There are a bunch of seperate commits in this PR:
---
Rename `get/set_property()` to `property_get/set_value()`.
This commit renames two of `NcpControlInterface` methods and updates
their use across wpantund source code:
- `property_set_value()` replacing `set_property()`,
- `property_get_value()` replacing `get_property()`.
---
Fix spacing/alignment and use tab for indentation
This commit contains no logic change and is cosmetic change only. It
makes the formating of method declarations in …
> Adding support for prop insert/remove value 

- src/wpanctl/wpanctl.c
This PR fixes the segment fault when using Ctrl-D to end **wpanctl**. #170
This is caused by not handling EOF in *readline* handler function.
*See*
[1] http://www.delorie.com/gnu/docs/readline/rlman_41.html
> Fix segment fault when use Ctrl-D to end wpanctl

- src/ncp-spinel/SpinelNCPInstance.cpp
This change fixes an issue where we could remain in the ISOLATED
state even after receiving an NCP event with role change to other
than detached.
Here is the flow to get stuck in isloated state
- A NCP role change to detached will trigger a `change_ncp_state(ISOLATED);`
- Later if we get a role change back to router, we won't change the wpantund state
- The change uses `ncp_state_is_joining_or_joined()` which includes the `ISOLATED` state to update.
> Ensure to switch to ASSOCIATED on NCP role change from detached

- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpanctl/tool-cmd-config-gateway.c
- src/wpantund/Makefile.am
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPInstanceBase-Prefixes.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
- add a property named "Thread:OnMeshPrefixes" which indicates the information about gateway (prefix, flags, and priority).
- add "priority" for configured prefix.
- provide "flags" (preferred, slaac, onMesh) for OT border router setting
> improve the config-gateway function

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.h
Fix a typo: "prase" should be "parse".
> Fix 'prase' typo

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/Makefile.am
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskPeek.cpp
- src/ncp-spinel/SpinelNCPTaskPeek.h
- src/wpanctl/Makefile.am
- src/wpanctl/tool-cmd-peek.c
- src/wpanctl/tool-cmd-peek.h
- src/wpanctl/tool-cmd-poke.c
- src/wpanctl/tool-cmd-poke.h
- src/wpanctl/wpanctl-cmds.h
- src/wpantund/NCPControlInterface.h
Peek command allows wpantund to fetch values from the NCP memory. Poke  command writes  bytes to a specified memory address on NCP. These commands are intended for debugging purposes.
The first commit contains the following:
- It defines peek/poke commands in `NCPControlInterface`.
- It implements peek/poke operation in spinel pluggin.
- It add new dbus API (v1) for peek and poke operations.
The second commit contains the implementation of "peek" and "poke" command in wpantcl.
> Adding support for "peek" and "poke" command in wpantund and wpanctl

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
This commit adds three new methods `update_link_local_address()`,
`update_mesh_local_address()` and `update_mesh_local_prefix()` to
refactor common code called from `value_is` and `value_inserted`
methods.
It also adds new logs in `handle_ncp_spinel_value_is` to show the
value received from NCP for certain spinel properties (e.g., network
name, PANID, XPANID,  channel, list of IPv6 addresses, and list of on-
mesh prefixes).
> Adding logs to show spinel property values and refactor common code

- src/ncp-spinel/SpinelNCPInstance.cpp
The on-mesh-prefixes from `ON_MESH_NETS` property includes both local and leader/network-wide list.  This commit adds the check to ensure that a SLAAC address is pushed to NCP only for non-local prefixes.
> Add SLACC address only for non-local on-mesh-prefixes

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
This commit adds support in spinel plug-in for detecting if the NCP
has saved network info (using property `SPINEL_PROP_NET_SAVED`) and
change the wpantund NCP state to  `COMMISSIONED` state. This change
help simplify the auto-resume implementation.
> Add support for "offline:commissioned"  state

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
This commit adds implementation for timeout functionality for`permit_join()` command in `SpinelNCPControlInterface`. It also modifies the logs in this method.
> Implement timeout for "permit-join" method in `SpinelNCPControlInterface`

- src/ncp-spinel/SpinelNCPTaskLeave.cpp
- src/wpantund/NetworkRetain.cpp
This commit contains two changes related to "Leave" operation:
- Clearing the flag `mIsCommisioned` from the `SpinelNCPTaskLeave()`.
- In `NetworkRetain` include the transmission from COMMISIONED to
OFFLINE to trigger the `erase_network_info()` call. This ensures
that any retained network info is erased in case AutoResume is
not enabled and "leave" is issued.
> Ensure to clear `mIsCommisioned` during "Leave"

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit also adds logs related to value of "NetworkPartitionId"
tied to `SPINEL_PROP_NET_PARTITION_ID`.
> Log neighbor table entries in syslog when parsing `SPINEL_PROP_THREAD_NEIGHBOR_TABLE`

- src/util/string-utils.c
This change addresses a one-byte buffer overflow in the function which parses a hex string into data, `parse_string_into_data()`. The buffer overflow would occur when the input string consisted of a single valid hexadecimal digit, and would result in the a byte with the valid of that digit in the upper nibble (and a zero in the lower nibble) being written to an invalid location in the stack.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3396
> string-utils: Fix for one-byte buffer overflow in parse_string_into_data

- src/wpantund/NCPInstanceBase.cpp
Several uninitialized variables were causing a lot of noise while fuzzing.
> NCPInstanceBase: Ensure all class variables are initialized.

- src/ncp-spinel/SpinelNCPInstance.cpp
Found via [oss-fuzz][] (issue [3394][chromium]).
[chromium]: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3394
[oss-fuzz]: https://oss-fuzz.com/v2/testcase-detail/6006849620934656
> ncp-spinel: Fix for NULL dereference on malformed packet

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
This seems to be causing some noise in the fuzzer and likely contributing to unpredictable behavior; so let's fix it.
Also removes `mDefaultChannelMask`, since it was unused.
> ncp-spinel: Ensure all SpinelNCPInstance member variables are initialized

- src/util/socket-utils.c
- src/util/string-utils.h
- src/util/tunnel.c
- src/wpantund/wpantund.cpp
This commit introduces two new functions to `string-utils.h`:
*   `strhasprefix(cstr, prefix)`: Returns true if the c-string `cstr`    is prefixed by the c-string `prefix`.
*   `strcasehasprefix(cstr, prefix)`: Case insensitive version of    `strhasprefix()`.
Previously, we were using `strncmp()` for this sort of thing. However, this is dangerous because when copying and pasting code it is easy to forget to update the prefix length argument. Indeed, this has happened several times. Using `strhasprefix()` will eliminate such problems.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3448#c3
> Replace fragile string prefix checks with `strhasprefix()`

- .travis.yml
This is a temporary work-around for issue #245.
> Temporary work-around for #245: Ignore macOS build failures

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
By default, the RLOC IPv6 addresses from NCP are filtered by wpantund
and are not added on the primary wpan interface. This commits adds a
new wpan property "Thread:Config:FilterRLOCAddresses" to allow user
to control/change this behavior. It is expected that this configuration
property  is set as part of `wpantund.conf` settings.
> npc-spinel: Allow user to control filtering of RLOC addresses

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds a new wpantund property "Thread:RouteTable" which
provides the list of all routers within the Thread network. This is
mapped to spinel `SPINEL_PROP_THREAD_ROUTER_TABLE`. This commit also
updated the `SpinelNCPTaskGetNetworkTopology` class to add support
for parsing a single router entry or entire router table.
The related PR in OpenThread: https://github.com/openthread/openthread/pull/2303
> Adding new property wpantund "Thread:RouterTable"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.h
This commit contains the following changes: (a) It updates the
`SpinelNCPTaskGetNetworkTopology` to provide a new  static method for
parsing of a single child table entry (which is also used in the
method for parsing the entire child table). (b) It also updates the
`handle_ncp_spinel_value_inserted/removed()` methods to parse and log
`CHILD_TABLE` updates from NCP.
> Handle and log child entry inserted/removed spinel messages from NCP

- src/ncp-dummy/DummyNCPInstance.cpp
- src/ncp-dummy/DummyNCPInstance.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/util/TunnelIPv6Interface.cpp
- src/util/TunnelIPv6Interface.h
- src/util/netif-mgmt.c
- src/util/netif-mgmt.h
- src/wpantund/NCPControlInterface.cpp
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase-AsyncIO.cpp
- src/wpantund/NCPInstanceBase-NetInterface.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
This commit adds support for managing off-mesh-routes from Thread
network. All off-mesh routes (aka external routes) from NCP or user-
added (e.g, using `add_external_route()`) are stored in a
`std::multimap` list `mOffMeshRoutes`. Property "Thread:OffMeshRoutes"
can be used to get the full list which contains information about the
origin of each entry along with preference level.
This commit also adds logic to manage the routes on wpan network
interface corresponding to the off-mesh routes from the network: A
route is added on wpan network interface if there is an off-mesh route
on at least one other device within network AND either the same route
is not added by the device itself, or if it is added, it is added with
a lower preference level from at least one other device within
network. …
> Managing off-mesh-routes and their mapping to interface routes

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
Getting this property will trigger a watchdog to happen on NCP. This
is intended for testing the watchdog functionality on NCP.
> Add new wpantund property "OpenThread:Debug:TestWatchdog"

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskSendCommand.h
The lock property `SPINEL_PROP_THREAD_ALLOW_LOCAL_NET_DATA_CHANGE` should be used when the underlying spinel propery would change the Thread Network Data (e.g., on-mesh prefixes or off-mesh routes). This commit fixes the extra/incorrect use of this lock property for other properties.
This should address https://github.com/openthread/openthread/issues/2110.
> Remove extra use of lock property `ALLOW_LOCAL_NET_DATA_CHANGE`

- src/util/SuperSocket.cpp
- src/util/time-utils.c
- src/util/time-utils.h
- src/wpantund/StatCollector.cpp
- src/wpantund/wpantund-fuzz.cpp
- src/wpantund/wpantund.cpp
- third_party/openthread/src/ncp/spinel.c
This commit should address the following [oss-fuzz](https://oss-fuzz.com/) issues:
* [3458](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3458)
* [4572](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4572)
* [3422](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3422)
* [3391](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3391)
* [3395](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3395)
* [3555](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3555)
* [3556](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3556)
The change to `spinel.c` needs to be backported to OpenThread.
> Fuzzer fixes

- src/wpantund/NCPInstanceBase-AsyncIO.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
This commit changes the behavior of `ncp_is_misbehaving()` such
that the reseting and reinitialization of NCP happens from the
main `NCPInstanceBase::process()`. This should help address the
following oss-fuzz issue:
* [4639](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4639)
> Let ncp_is_misbehaving() trigger an NCP reset/reinit from process()

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds a new wpan property "Thread:ChildTable:Addresses"
which is mapped to SPINEL_PROP_THREAD_CHILD_TABLE_ADDRESSES. This
property provides the list of all addresses associated with every
child including any registered IPv6 addresses.
This commit also simplifies class SpinelNCPTaskGetNetworkTopology
implementation by adding a new `parse_table()` method which includes
the common code used for parsing different spinel properties related
to network topology (child table, neighbor table, router table, etc).
Related PR in OT: https://github.com/openthread/openthread/pull/2434
> Adding new property "Thread:ChildTable:Addresses"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/util/IPv6PacketMatcher.cpp
- src/util/nlpt-select.c
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/wpantund-fuzz.cpp
- src/wpantund/wpantund.cpp
[oss-fuzz-3565](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3565) describes an unreproducable (but frequently occuring) global buffer overflow discovered by fuzzing. The immediate cause of the overflow is the failure of `fd_set_merge()` to respect the size boundaries of an `fd_set`, which is limited to accounting to no more than `FD_SETSIZE` file descriptors.
However, the fact that we are getting anywhere close to the `FD_SETSIZE` file descriptor limit indicates that we may very well be leaking file descriptors. As such, this commit adds a quick file descriptor leak check, intended to help identify file descriptor leaks more quickly.
Such a file descriptor leak is likely to only be a practical problem for fuzzing efforts, since the normal instance of wpantund would only ever …
> Speculative/Diagnostic fix for oss-fuzz-3565

- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.h
This pull request solves problem with building latest wpantund on the RPi3 platform. During building the border router I've got an error which says that cannot bind bitfields variables with their names. e.g. ```SpinelNCPTaskGetNetworkTopology.cpp:698:83: error: cannot bind bitfield ((nl::wpantund::SpinelNCPtaskGetNetworkTopology::TableEntry*)this)->nl::wpantund::SpinelNCPTaskGetNetworkTopology::TableEntry::mRxOnWhenIdle to bool&```.
> Fix problem with building wpantund.

- etc/fuzz-corpus/wpantund-fuzz/oss-fuzz-3565
- src/util/SuperSocket.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/wpantund-fuzz.cpp
This commit fixes a bug in the previous diagnostic update that prevented the new code from properly identifying file descriptor leaks.
It also fixes the original file descriptor leak that led to [oss-fuzz-3565](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3565) in the first place.
> Fix and update for oss-fuzz-3565

- src/util/SocketAdapter.cpp
- src/util/SocketAdapter.h
- src/util/SocketWrapper.cpp
- src/util/SocketWrapper.h
- src/util/UnixSocket.cpp
- src/util/UnixSocket.h
- src/wpantund/NCPInstanceBase-AsyncIO.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpantund.cpp
[oss-fuzz-5238](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5238) identified a minor file descriptor leak which was interrupting fuzzing efficiency (but would not affect normal operation). This commit addresses that leak.
> Fix for minor file descriptor leak

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support for new properties related to OpenThread's
Channel Monitoring feature. This feature allows the NCP to periodically
monitor all channels to help determine the cleaner channels (channels
with less interference).
Related PR in OpenThread: https://github.com/openthread/openthread/pull/2462
> Adding properties related to for Channel Monitoring feature

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commits adds support for two new wpantund properties "NCP:Counter:AllMac" and "NCP:Counter:AllMac:AsValMap" to get all the NCP MAC counters with a single property get. These are mapped to spinel property SPINEL_PROP_CNTR_ALL_MAC_COUNTERS.
---------------------
Related PR in OT: https://github.com/openthread/openthread/pull/2489
```
wpanctl:wpan1> get NCP:Counter:AllMac
NCP:Counter:AllMac = [
"TxTotal              = 80"
"TxUnicast            = 9"
"TxBroadcast          = 71"
"TxAckRequested       = 8"
"TxAcked              = 8"
"TxNoAckRequested     = 72"
"TxData               = 80"
"TxDataPoll           = 0"
"TxBeacon             = 0"
"TxBeaconRequest      = 0"
"TxOther              = 0"
"TxRetry              = 0"
"TxErrCca             = 0"
"TxErrAbort           = 0"
"TxErrBusyChannel …
```
> Add new property to get all NCP MAC counters

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
The wpan property is mapped to newly added NCP spinel property
`SPINEL_PROP_MAC_CCA_FAILURE_RATE` which provides the CCA
(Clear Channel Assessment) failure rate. The value is provided
as a `uint16_t` with 0 mapping to 0% error rate, and 0xffff
indicating 100% failure rate.
> Add new wpan property "NCP:CCAFailureRate"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds new wpan property to get the message or frame error
rates of all neighbors from NCP. The value can be returned as a
human-readable string list, or as a `ValueMap` list.
Related PRs in OT: https://github.com/openthread/openthread/pull/2525 and https://github.com/openthread/openthread/pull/2520
Here is how the output would look like:
```
wpanctl:wpan1> get Thread:NeighborTable:ErrorRates
Thread:NeighborTable:ErrorRates = [
"3688BF2C2F0FC27F, RLOC16:0800, FrameErrRate:25.89%, MsgErrorRate:1.34%, AveRssi:-20, LastRssi:-20, "
"3684CBF2F0E15EB4, RLOC16:7400, FrameErrRate:14.16%, MsgErrorRate:0.77%, AveRssi:-20, LastRssi:-20, "
"028844B586722E36, RLOC16:8000, FrameErrRate:0.78%, MsgErrorRate:0.00%, AveRssi:-20, LastRssi:-20, "
]
wpanctl:wpan1> get …
```
> Add new wpan property "Thread:NeighborTable:ErrorRates"

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit adds `SPINEL_PROP_IPV6_ADDRESS_TABLE` to the list of
properties that are fetched from `handle_ncp_state_change()` after
an NCP state change to "associated".
> Get full IPv6 address table on NCP state change to "associated"

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
This commit adds two new `wpantund` daemon configuration properties:
- `"Daemon:OffMeshRoute:AutoAddOnInterface"` - This boolean property determines whether `wpantund` should manage the routes on the primary interface. When set to `true` wpantund will add/remove off-mesh routes provided by devices within the network on the host interface. Otherwise, it is expected the routes would be managed externally. By default this feature is enabled (`true`).
- `"Daemon:OffMeshRoute:FilterSelfAutoAdded"` - This boolean property controls how the off-mesh-routes are managed on the primary interface (this is applicable only if the `AutoAddOnInterface` feature is enabled). 
This property impacts the behavior where the same off-mesh route is provided by multiple devices within the network including the …
> Properties to control how off-mesh-routes are managed on primary interface

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
This commit adds a new configuration option to determine whether
wpantund should listen for unicast IPv6 address-added/removed events
from the primary interface and then update the addresses on the NCP.
By default this feature is enabled. It can be changed using a
corresponding configuration wpantund property.
> Add config option "Deamon::IPv6::AutoUpdateInterfaceAddrsOnNCP"

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
This commit adds a new configuration option to determine whether
wpantund should skip adding user (or interface) originated link-local
IPv6 addresses on NCP. By default this feature is enabled. The
behavior can  be changed using wpantund configuration property
"Daemon:IPv6:FilterUserAddedLinkLocal".
> Add config option "Daemon:IPv6:FilterUserAddedLinkLocal"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskForm.cpp
Add support to explicitly configure mesh local prefix.
I am not very clear why configuring the network parameters again when forming the network, but, one issue when adding `IPv6:MeshLocalPrefix` set operation is that it would be replaced by the one coming from XPANID because mesh local prefix would be configured again when configuring XPANID again during forming (see https://github.com/openthread/openthread/blob/master/src/core/api/thread_api.cpp#L83). So another change in this PR is to prefer the mesh local prefix explicitly configured by property to the one from mesh local address.
@abtink, please help to evaluate if it has any possible issue I didn't notice. Thanks.
> add mesh local prefix setting support

- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
Fix incorrect use of `=` instead of `==`.
> Fix incorrect comparision in `SpinelNCPTaskGetNetworkTopology`

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support for new wpan properties related
to "Channel Manager" feature. This feature allows user
to request a channel change or request NCP to select a
channel based on NCP's collected link/channel quality data.
> Implement properties related to "Channel Manager" OT feature

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskDeepSleep.cpp
- src/ncp-spinel/SpinelNCPTaskWake.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
It adds support for getting/setting a new property "NCP:MCUPowerState"
in wpantund. This property is mapped to the recently added spinel
property `SPINEL_PROP_MCU_POWER_STATE` which can be used to control
the NCP's MCU power state (capability `SPINEL_CAP_MCU_POWER_STATE`
indicates support for this property and feature on NCP).
The `SpinelNCPTaskDeepSleep` and `SpinelNCPTaskWake` implementations
are updated to adopt/use the new spinel property (only when the NCP is
indicating its capability for this feature).
The commit also adds logic to manage wpantund state changes between
`OFFLINE` and `DEEP_SLEEP` based on changes to `MCU_POWER_STATE`.
Finally, `SpinelNCPControlInterface::begin_low_power()` is changed to
be an alias for setting the property …
> Add support for NCP MCU power state control and deep-sleep mode

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
This commit fixes an issue with the auto-resume logic not starting
when the NCP starts with MCU in low-power (wpan state starting as
"offline:deep-sleep". It changes the test before starting the resume
process to explicitly check the `mIsCommisionned` flag and relax
the wpan state check to include any offline states.
> Allow auto-resume from wpan "offline:deep-sleep" state

- .travis.yml
- .travis/script.sh
This commit enables [`toranj`](https://github.com/openthread/openthread/blob/master/tests/toranj/README.md) tests to be run as part of wpantund travis CI.
> Enabling "toranj" test-framework on wpantund travis CI

- src/ncp-spinel/Makefile.am
This commit disables the `ncp-spinel-fuzz` target (note that the target
is only commented out in `ncp-spinel/Makefile.am` to keep it for a
possible future use).
Should help address: https://github.com/google/oss-fuzz/issues/1328
> Disable ncp-spinel-fuzz target

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
This commit adds new feature to allow user to add/remove multicast
IPv6 addresses by issuing insert/remove using the wpan property
"IPv6:MulticastAddresses". The multicast IPv6 address will be updated
on NCP and also on the primary network interface.
> Enable adding/removing multicast IPv6 addresses

- src/connman-plugin/wpan-connman-plugin.c
Issue flagged by the clang security checker.  Actual impact to product
is minimal -- the string being used as a source comes from dbus.  If
it was malicious it would be either because the attacker has a daemon
on the device already or because she has somehow hacked the pairing
flow into passing around a wrong network prefix.  At that point, a
buffer overrun and a resulting stack corruption would be the least of
our issues.  Nonetheless, it is best practice to check lengths so
that's what we're doing here.
> Replace an unchecked strcpy with a better strncpy

- src/ncp-spinel/SpinelNCPInstance.cpp
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit updates "spinel.h", and "spinel.c" files from OpenThread
(commit b76f72e1ac85). It also addresses the spinel property name
change to `SPINEL_PROP_CHANNEL_MONITOR_CHANNEL_OCCUPANCY` from
`SPINEL_PROP_CHANNEL_MONITOR_CHANNEL_QUALITY`. The spinel property
key and its encoding remain unchanged (this is only a name change).
> Update spinel header files

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
This commit makes a change in the NCP initialization protothread  code
in `vprocess_init()` where the `mDriverState` is changed to
`INITIALIZING` (from `INITIALIZING_WAITING_FOR_RESET`) earlier in the
code and before sending a command to get the NCP protocol version.
This ensures that any received resets from NCP cause the protothread
to be restarted immediately.
This change addresses a delay issue with `wpantund` starting, where if
NCP is reset (e.g., by `spi-hdlc-adapter` process starting) while
wpantund is performing the NCP initialization, a wait time delay equal
to command response timeout (5 seconds) may be required for
initialization to restart.
> Allow NCP reset to restart the initialization protothread earlier

- src/ncp-spinel/Makefile.am
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPVendorCustom.cpp
- src/ncp-spinel/SpinelNCPVendorCustom.h
The SpinelNCPVendorCustom class is where vendor-specific spinel extensions can be implemented. It allows all vendor-specific code to live in a single file to improve the merging experience.
Note that this class is a placeholder in the main wpantund repository. Vendor properties MUST NOT be added to this class in the main wpantund repository.
> spinel: Added new SpinelNCPVendorCustom class

- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support for the new NCP log output model. It adds
support for the newly added spinel property `SPINEL_PROP_STREAM_LOG`
which provides streaming of formatted log string from NCP along with
an optional metadata structure. OpenThread log level and log region
are included as part of the metadata. `wpantund` parses the metadata
and appends a human-readable prefix string to the outputted log line
in syslog.
Related PR in OT: https://github.com/openthread/openthread/pull/2722
> Add support for new NCP log output model and spinel property

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit removes some dead, redundant code related to setting the network key. The removed code doesn't ever get executed because the network key actually gets handled earlier in the method.
> spinel: Remove dead code related to setting Network Key

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
This commit adds new wpan property to configure the jitter
for Router-Capable device to decide whether to become Router or
stay in REED role.
> Add new wpan property "Thread:RouterSelectionJitter"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
This commit adds two new properties, "Thread:RouterUpgradeThreshold"
and "Thread:RouterDowngradeThreshold".
> Adding properties to get/set Thread Router Upgrade/Downgrade Threshold

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support to get the Thread EID IPv6 address cache
table. New wpantund property "Thread:AddressCacheTable" is added
which is mapped to spinel property `THREAD_ADDRESS_CACHE_TABLE`.
When a `VALUE_IS` update is received from NCP for the spinel
property `THREAD_ADDRESS_CACHE_TABLE`, the cache table info is
added to the logs.
-----
PR in OpenThread: https://github.com/openthread/openthread/pull/2788.
```
$ Node1.wpanctl('get -v Thread:AddressCacheTable')
[
"fdf6:64b8:62e7:0:f635:590d:53bb:10b3 -> 0x4c02, age:0"
"fdf6:64b8:62e7:0:6d8b:f045:eb1f:adb8 -> 0x4c00, age:1"
"fdf6:64b8:62e7:0:d18:18a4:6e89:5c00 -> 0x4c00, age:2"
]
$ Node1.wpanctl('get -v Thread:AddressCacheTable:AsValMap')
[
[
"Address" => "fdf6:64b8:62e7:0:f635:590d:53bb:10b3"
"Age" => 0x00
"RLOC16" => 0x4C02
]
[ …
```
> Add new property "Thread:AddressCacheTable"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
This property is mapped to spinel `NET_KEY_SWITCH_GUARDTIME` property.
> Adding new property "Network:KeySwitchGuardTime"

- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v1.cpp
In some of `DBusIPCAPI_v1` or `DBusIPCAPI_v0` interface methods
`dbus_message_ref()` was called twice on the DBus `message`. This
commit removes the extra call.
> Remove extra `dbus_message_ref()` in DBus APIs methods

- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/wpanctl/Makefile.am
- src/wpanctl/tool-cmd-add-prefix.c
- src/wpanctl/tool-cmd-add-prefix.h
- src/wpanctl/tool-cmd-config-gateway.c
- src/wpanctl/tool-cmd-remove-prefix.c
- src/wpanctl/tool-cmd-remove-prefix.h
- src/wpanctl/wpanctl-cmds.h
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.h
- It updates the `NCPControlInterface::add_on_mesh_prefix()` to
accept a `std::set<PrefixFlag>` along with `stable` status and
prefix length.
- It updates the control interface implementation for Spinel and Dummy
plugins to adopt the new on-mesh prefix API.
- It updates DBus API implementations (v0 and v1) to use the new
control interface API
- It extends the DBus `CONFIG_GATEWAY` method to allow for new
arguments (flag info, stable status, prefix_len) to be provided
while keeping it backward compatible with earlier pattern.
- It adds two new `wpanctl` commands `add-prefix`/`remove-prefix`
which allow user to fully specify all prefix flags and options.
> New APIs for adding/removing on-mesh prefix

- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/wpanctl/tool-cmd-add-route.c
- src/wpanctl/tool-cmd-remove-route.c
- src/wpantund/NCPControlInterface.h
- It updates the `NCPControlInterface::add_external_route` API to
include the stable flag as an input argument
- It updates the implementation of the control interface API on
Spinel and Dummy plugins to adopt the new model.
- It updates the DBUs API (v1) `ROUTE_ADD` to allow the stable
flag as an argument, while staying backward compatible with
previous format.
- It updates wpanctl `add-route` to allow adding a route prefixes
with "stable" flag.
- It also updates `add-route` and `remove-route` wpanctl commands
to specify the route prefix length in bits (instead of bytes).
> Add support to specify "stable" flag for off-mesh routes

- .gitignore
src/version.c isn't in gitignore, which can cause issues for automatic
syncs. The automatic sync fail will due to uncommitted changes even though
this file is generated by the build system and should be ignored.
> Add autogenerated version file to git ignore

- Android.mk
spi-hdlc-adapter will now be built along with wpantund and wpanctl.
> Add spi-hdlc-adapter to Android.mk

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/wpantund/NCPInstanceBase.h
This commit adds support in wpantund to set "NCP:ChannelMask".
It also updates how the supported channel mask is tracked by the
`SpinelNCPInstance` and used by `form` command tasks.
------
Related PR in OT: https://github.com/openthread/openthread/pull/2838
> Enable setting of "NCP:ChannelMask"

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.h
This commit adds new wpan properties "Thread:Parent" and
"Thread:Parent:AsValMap" to provide info about parent of device
when attached as a child (end-device).
Related PR in OpenThread: https://github.com/openthread/openthread/pull/2854
> Add wpan property "Thread:Parent" to get parent info

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This PR replaces TMF proxy with UDP proxy, which helps moving border agent into OpenThread. The changes in OpenThread can be reviewed at https://github.com/openthread/openthread/pull/2771
> Replace TMF proxy with UDP proxy

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPThreadDataset.cpp
- src/ncp-spinel/SpinelNCPThreadDataset.h
- src/wpanctl/tool-cmd-dataset.c
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support to send `MGMT_GET` meshcop command for
Active/Pending Operational Dataset. wpanctl `dataset` is also
updated to add new commands.
This commit also adds a new wpan property "Dataset:DestIpAddress"
to help specify the destitaion IPv6 address for sending MGM_GET
command.
> Add support for sending MGMT_GET for Active/Pending Dataset

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
This commit change how the on-mesh prefix list is maintained by
`wpantund` to allow for instances of same prefix added by different
nodes within the Thread network (possibly with different flags) to be
tracked individually.  This commit also changes the behavior when an
IPv6 address is added with an existing prefix (e.g., prefix already
added by another node). In such case the prefix will be re-added by
the node adding the new IPv6 address.
> Allow multiple instances of same on-mesh prefix to be tracked separately

- src/util/string-utils.c
This commit fixes an issue in `encode_data_into_string()` where
the last byte may be missed in string representation.
> Fix the `encode_data_into_string()` implementation

- src/wpanctl/tool-cmd-form.c
- src/wpanctl/tool-cmd-join.c
- src/wpanctl/wpanctl-utils.c
- src/wpanctl/wpanctl-utils.h
This commit enhances the implementation of `form` and `join` wpanctl
commands to use wpantund DBus v1 APIs (instead of v0). New (v1) APIs
are more flexible and allow a dictionary of property key (as string),
property value (as DBus variant type) to be provided as input. Both
`form` and `join` wpanctl commands are updated to allow more
(optional) parameters to be specified: `form` allows panid, xpaind,
network key, key index, mesh-local-prefix channel mask to be
optionally provided as part of the `form` command in addition to
network name and/or channel. `join` allows network key to be specified
as part of `join` command itself.
> Update wpanctl `form` and `join` implementation to use DBus v1 APIs

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/wpantund/NCPInstanceBase.cpp
1) It adds new code to restart the main proptothread from
`SpinelNCPInstance::vprocess_event()` when driver is enabled again
after a driver disable. This ensures internal state stays in sync
with NCP and that the network is resumed if `mAutoResume` feature
is enabled.
2) The code changes how the interface is taken offline when driver
is disabled.
It updates `NCPInstanceBase::handle_ncp_state_change()` to ensure
when driver is disabled causing a transition to `COMMISSIONED`
state even if `mAutoResume` is enabled, the network interface(s)
are taken down.
It also removes the call from `vprocess_disabled()` protothread
to bring down the interface.
> Re-initialize NCP on driver start after a stop

- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
This commit adds `log_spinel_frame()` which implements the code to
log sent or received spinel frame info, including the spinel command
and in case of property change (e.g., `VALUE_GET`, `VALUE_SET,
`VALUE_IS`, etc.) the property key and also hex dump of the
encoded value of the property.
> Add a common method to log sent/received spinel frame info

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
This commit adds a new property "NCP:Capabilities" to get a human-
readable list of capabilities provided by the NCP.
-------------------
Here is how the output looks like:
```
wpanctl:wpan1> get NCP:Capabilities
NCP:Capabilities = [
"COUNTERS (5)"
"JAM_DETECT (6)"
"UNSOL_UPDATE_FILTER (12)"
"MCU_POWER_STATE (13)"
"802_15_4_2450MHZ_OQPSK (24)"
"ROLE_ROUTER (48)"
"ROLE_SLEEPY (49)"
"NET_THREAD_1_0 (52)"
"MAC_WHITELIST (512)"
"OOB_STEERING_DATA (514)"
"CHANNEL_MONITOR (515)"
"ERROR_RATE_TRACKING (516)"
"CHANNEL_MANAGER (517)"
"OPENTHREAD_LOG_METADATA (518)"
"CHILD_SUPERVISION (520)"
"THREAD_COMMISSIONER (1024)"
"NEST_LEGACY_INTERFACE (15296)"
]
```
> Add new property to get list of NCP capabilities

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
This commit adds a new feature and a related configuration property
"Daemon:IPv6:AutoAddSLAACAddress". This boolean property indicates
whether wpantund would generate and add an SLAAC address when an an
on-mesh prefix with the SLAAC flag is added. The SLAAC address is
added only if there is no existing address with the same prefix. By
default this feature is enabled (i.e. SLAAC addresses are added). It
can be changed using the above property during run-time or from
`wpantund.conf` file.
> Add feature to control auto-addition of SLAAC address by wpantund

- src/ncp-spinel/spinel-extra.h
- src/util/config-file.h
- src/util/netif-mgmt.h
- src/util/nlpt-select.h
- src/util/sec-random.h
- src/util/socket-utils.h
- src/util/string-utils.h
- src/util/time-utils.h
- src/util/tunnel.h
- src/version.h
- src/wpantund/wpan-error.h
- src/wpantund/wpantund.cpp
- third_party/openthread/src/ncp/spinel.h
The `sys/cdefs.h` is an internal header of `glibc` and is not meant to
be used by user code.  The macros needed from it can be trivially
implemented where required, relying on this header being present
excludes `wpantund` from being used on systems where `glibc` is not the
used C library (e.g. OpenWRT, where `uclibc` or `musl` is standard).
https://wiki.musl-libc.org/faq.html#Q:-When-compiling-something-against-musl,-I-get-error-messages-about-%3Ccode%3Esys/cdefs.h%3C/code%3E
> Do not use glibc-internal header sys/cdefs.h

- Android.mk
spi-hdlc-adapter is third party and is used by OpenThread itself,
building spi-hdlc-adapter in OpenThread can simplify and accelerate
fixing bugs.
> Move building spi-hdlc-adapter to OpenThread

- src/ncp-spinel/SpinelNCPTaskJoin.cpp
For existing wpanctl 'join' cmd, it would assume the ncp with FTD option enabled and always configure SPINEL_PROP_THREAD_ROUTER_ROLE_ENABLED property, however for ncp with only MTD option enabled, this property is not supported.
> [cert] OpenThread MTD build

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
If FilterRLOCAddresses option is enabled, then we can decide whether
ALOC addresses should be filtered using additional option
FilterALOCAddresses. Default value of FilterALOCAddresses is 'true',
so it's backward compatible - filtering behaviour will not change if
this option is not defined in wpantund.conf.
>  FilterALOCAddresses option added

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds a new wpan property "NCP:Counter:Thread:Mle" to
get the Thread MLE counters (either as human-readable string or as
a value-map dictionary).
Related PR in openthread: https://github.com/openthread/openthread/pull/3558
> Add support to get Thread MLE counters

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
This commit adds RCP version to output of "wpanctl status" command
when POSX_APP capability is present in the list of NCP capabilities.
To enable this, `SpinelNCPInstance` is changed to save the RCP
version. A new property "POSIXApp:RCPVersion:Cached" is added to
get the cached value. Note that to ensure `status` command is
quick (does not block) all reported properties in `status` output
are cached. The `vprocess_init()` protothread is also updated to
retrieve RCP version during initialization.
> Add RCP version to "wpanctl status" when available

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds new wpan properties to control SLAAC behavior on
NCP (if supported). It adds "OpenThread:SLAAC:Enabled" wpan property
to check status of SLAAC on NCP/OpenThread. The new code also
ensures to disable SLAAC address addition by `wpantund` if NCP
already supports SLAAC.
> NCP supporting SLAAC

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.cpp
- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.h
- src/wpanctl/tool-cmd-joiner.c
- src/wpantund/NCPControlInterface.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.h
This commit updates the Joiner related implementation in `wpantund`,
mainly adding support for user to specify the vendor related parameters
(name, model, SW version, and data) when joiner commissioning starts.
The following changes are included in this commit:
- The `NCPControlInterface` API `joiner_commissioning()` is changed to
get all parameters as a `ValueMap` dictionary `options` (aligns it to
to follow the same pattern used by other APIs like `form()` and
`join()`). Along with this a group of value-map keys are defined for
all parameters (PSK, provisioning URL, vendor info) in
`wpan-properties.h`.
- The `SpinelNCPTaskJoinerCommissioning` implementation is changed to
use a `ValueMap` dictionary as its input and intercat with NCP using
the new specification of …
> Updating Joiner support - vendor parameters

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit adds `SPINEL_PROP_MESHCOP_JOINER_COMMISSIONING`,
`SPINEL_PROP_NET_PSKC`, and `SPINEL_PROP_MESHCOP_COMMISSIONER_JOINERS`
to the list of spinel properties for which the `log_spinel_frame()`
skips the value dump. This is to ensure PSK strings are not included
in the logs.
> When logging, hide values of spinel properties related to PSK(c/d)

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.h
This commit changes `"Thread:Joiner:State"` property to return a
string indicating the Joiner state (instead of enumeration value).
Valid Joiner state strings are defined in `wpan-properties.h`
header file (as `kWPANTUNDThreadJoinerState_<state>`).
> "Thread:Joiner:State" returning string 

- src/wpantund/NCPInstanceBase.h
Missing these constructors will cause warnings which are treated as
errors.
> [build] add missing virtual destructors

- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.cpp
- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.h
- src/wpanctl/tool-cmd-joiner.c
- src/wpantund/NCPConstants.h
- src/wpantund/wpan-error.c
- src/wpantund/wpan-error.h
- src/wpantund/wpan-properties.h
This commit updates the Joiner Commissioning implementation to  add
support for blocking mode where upon Joiner start wpantund would wait
till end of operation and returns a wpan error indicating the reason
for failure including no peers, security (incorrect PSKd), response
timeout, etc. This feature is added by introducing a new value-map key
"Joiner:ReturnImmediatelyOnStart" to joiner API options which
indicates if on start of operation, we should return immediately or
wait for final status.
wpanctl `joiner` command is also updated to allow the blocking join
model using `--join` or `-j` command.
> Update Joiner support (enable blocking mode and return joiner error)

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.cpp
- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.h
- src/wpanctl/tool-cmd-joiner.c
- src/wpantund/NCPControlInterface.h
This commit updates the `joiner_attach()` method to allow it to be
either blocking (wait till device attaches and state changes to
"associated") or non-blocking (which is the existing behavior). A new
sub-command `--attach-blocking` is added to wpanctl `joiner` command
for this new function.
> Update "Joiner Attach" to allow blocking behavior

- src/wpanctl/tool-cmd-mfg.c
Some diagnostic is much longer than 256. `1300` can cover those commands.
> [diag] allow longer command line for diagnostic

- src/util/DBUSHelpers.cpp
This commit enhances `DBUSHelpers::value_map_from_dbus_iter()` to
allow it to parse an empty DBus iter into a message as an empty
`ValueMap` dictionary. This addresses the case where a DBus command
(e.g., "JoinerAttach") is issued with no parameters (no appended DBUs
dictionary) expecting default parameters to be used for the command.
> Parse an empty DBUs message as an empty ValueMap dictionary

- src/ncp-spinel/SpinelNCPInstance.cpp
---
This is related to https://github.com/openthread/openthread/pull/3838
Example of how the  entries are loggd:
```
wpantund[60873]: [-NCP-]: Neighbor(Router) entry added: 1B007E862ACBA011, RLOC16:0f82, LQIn:0, AveRssi:0, LastRssi:0, Age:51200, LinkFC:196875, MleFC:327680, IsChild:yes, RxOnIdle:no, FTD:yes, SecDataReq:no, FullNetData:yes
wpantund[60873]: [-NCP-]: Neighbor(Router) entry added: 1B00428DC3508D20, RLOC16:78b6, LQIn:0, AveRssi:0, LastRssi:0, Age:36864, LinkFC:327947, MleFC:917504, IsChild:yes, RxOnIdle:no, FTD:yes, SecDataReq:no, FullNetData:yes
```
> Log neighbor/router entry added/removed events from NCP

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit update spinel source files from OpenThread at commit
dbc04a8a0. This commit brings in the following change from OpenThread
"[spinel] validate decoded/unpacked UTF8 string (#3889)" which
ensures a decoded string follows UTF8 encoding.
> Update spinel files from OpenThread (#418)

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit initializes the boolean `stable` variable (this is to
address an oss-fuzz issue). It also updated the related to log to
use a string "yes"/"no" to indicate if the entry is stable or not.
> Initialize bool variable when parsing SERVIES list

- src/util/socket-utils.c
This changes socket-utils to use default value if baud rate is
not known/detemined. This was changed recently in 5a664c16e (which
causes issues with oss-fuzz tests). This commit changes the
behavior back.
> [socket-utils] use default if baud rate is not known

- .travis.yml
The android build system requires an old version of make, which is not
available in the latest build environment of Travis. This PR sets the
dist to trusty for Android check.
> Use trusty for android check

- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskGetMsgBufferCounters.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/ncp-spinel/SpinelNCPTaskHostDidWake.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.cpp
- src/ncp-spinel/SpinelNCPTaskLeave.cpp
- src/ncp-spinel/SpinelNCPTaskPeek.cpp
- src/ncp-spinel/SpinelNCPTaskScan.cpp
This commit changes the `NCPTask<Command>` protothread such that at
the start we wait for the end of any ongoing NCP initialization.
This commit adds the condition `!mInstance->is_initializing_ncp()` in
addition to checking of ncp state. Note that ncp state from
`get_ncp_state()` itself may change during initialization while
driver is syncing with NCP.
> Wait till end of NCP init when starting a new command task

- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPTaskSendCommand.cpp
- src/ncp-spinel/SpinelNCPTaskSendCommand.h
This commit convert the `SpinelNCPControlInterface::reset()` API to
wait till end of NCP re-initilaization (instead of returning after
issuing the `RESET` command to NCP). This is realized by adding a
feature in `TaskSendCommand` to allow an optional "final check
handler" to be added to the command. If provided after the commands
are sent to NCP, the task will invoke the provided handler and waits
until the handler returns `true` (within the given timeout interval).
> Make "reset" wait till end of NCP init

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds  "SPINEL_PROP_RADIO_COEX_METRICS" to the list of spinel properties. It adds "kWPANTUNDProperty_NCPCoexMetrics" and "kWPANTUNDProperty_NCPCoexMetricsAsValMap" wpan properties to get the radio coex metrics.
> Add thread radio coex metrics support

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds "SPINEL_PROP_RADIO_COEX_ENABLE" to the list of spinel properties and
add "kWPANTUNDProperty_NCPCoexEnable" wpan properties to enable/disable the radio coex.
> Add thread coex enable/disable properity

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
- src/wpantund/wpan-properties.h
This commit adds a new feature in `wpantund` to auto add a route on
the host primary interface corresponding to on-mesh prefixes from
Thread network.
This feature can be enabled through a newly added wpan property with
name "Daemon:OnMeshPrefix:AutoAddAsIntterfaceRoute" which is enabled
by default.
When enabled, wpantund would add a route on host primary interface for
any prefix from thread network (with on-mesh flag set). This in turn
ensures that traffic destined to an IPv6 address matching the prefix
would be correctly forwarded to the `wpan` interface on host.
----
This feature is now independent of `mAutoAddOffMeshRoutesOnInterface` (each feature can be separately enabled or disabled).
https://github.com/openthread/openthread/pull/4221 adds a test-case to cover the behavior of this …
> Feature to auto add on-mesh prefixes as interface route

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/wpanctl/commissioner-utils.h
- src/wpanctl/tool-cmd-commr.c
- src/wpantund/NCPConstants.h
- src/wpantund/NCPControlInterface.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support in wpantund and wpanctl to generate PSKc
from a given commissioning pass-phrase, network name and XPANID.
The spinel property `SPINEL_PROP_MESHCOP_COMMISSIONER_GENERATE_PSKC`
is used for this purpose. A new DBUS API (v1) is added to expose
this functionality to other processes. wpanctl `commissioner`
command is updated to provide `gen-pskc`.
----
Related PR in OpenThread: https://github.com/openthread/openthread/pull/4294
> Add support for generating PSKc from pass-phrase, net-name, and XPANId

- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/ncp-spinel/SpinelNCPTaskJoin.cpp
- src/util/any-to.cpp
- src/util/any-to.h
This commit updates `any_to_uint64()` to allow a string representing
to be optionally treated as a number (decimal number or hex value
starting with `0x`). This change relaxes the input format when setting
`"Dataset:Active/PendingTimestamp"` properties, while keeping the parsing
of XPANID as before (expecting it to be a 16 char hex value).
-------------
Here is the new code in action:
```
wpanctl:wpan1> set Dataset:ActiveTimestamp 7
wpanctl:wpan1> get Dataset:ActiveTimestamp 
Dataset:ActiveTimestamp = 0x0000000000000007
wpanctl:wpan1> set Dataset:PendingTimestamp 0x1234567
wpanctl:wpan1> get Dataset:PendingTimestamp
Dataset:PendingTimestamp = 0x0000000001234567
wpanctl:wpan1> set Dataset:PendingTimestamp -d 1122334455667788
Dataset:PendingTimestamp = 0x1122334455667788
wpanctl:wpan1> set …
```
> Relax parsing of set value on "Dataset:Active/PendingTimestamp"

- src/ncp-spinel/SpinelNCPControlInterface.cpp
Wrap string literal in std::string to avoid assigning a char array to
boost::any
> Fix compile error boost::any:array used as initializer

- Android.mk
Some platform doesn't export /dev/net/tun
This reverts commit 5f7a39d4220ec8f48287646f61716eb71dff3a56.
> Revert "[misc] Use /dev/net/tun with non-root access in Android.mk

- src/ncp-spinel/SpinelNCPTaskScan.cpp
This commit relaxes the NCP state check in `TaskScan` (when performing
a discover scan) to allow discover scan to be performed in any offline
state (in particular "offline:commissioned").
> Relax the "discover scan" check for bringing NCP interface up

- src/util/TunnelIPv6Interface.cpp
- src/util/TunnelIPv6Interface.h
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
Currently using IP6_JOIN_GROUP to listen on multicast addresses won't
notify wpantund. This patch listens for a MLD report and updates the
multicast group to the NCP.
Test script:
``` python
#!/usr/bin/env python3
import socket
import struct
import sys
s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
s.bind(('ff02::158', 30000))
s.setsockopt(socket.IPPROTO_IPV6,       socket.IPV6_MULTICAST_IF, int(sys.argv[1]))
s.setsockopt(socket.IPPROTO_IPV6,       socket.IPV6_JOIN_GROUP, 
struct.pack('16si', socket.inet_pton(socket.AF_INET6, 'ff02::158'), int(sys.argv[1])))
while True:
print(s.recvfrom(4096))
```
Run wpantund and run the script with the first argument as the wpan0 interface index.
You can see the multicast group added to and removed from the NCP when the script starts/exits.
> Listen for MLD report to add/remove multicast groups

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
* Handle timestamp field in log metadata introduced by:
https://github.com/openthread/openthread/pull/4439
* Add new property "OpenThread:LogTimestampBase" that can be used to change the NCP log base timestamp
This change does not break the compatibility: older wpantund will work with newer OpenThread and newer wpantund will work with older OpenThread.
> Handle timestamp log metadata received from NCP

- Android.mk
- src/util/netif-mgmt.c
Always use the missing strlcpy header in case strlcpy is not provided
in the system library. This header will define strlcpy as a macro which
points to __missing_strlcpy.
> [util] include missing strlcpy header

- src/ncp-spinel/SpinelNCPInstance.cpp
This PR supresses outputting an error message when setting an async
property during initialization, which is misleading.
> Do not output error for setting an async property

- src/util/Data.h
---
If `std::vector` happens to be empty, we protect against  dereference of `begin()` iterator.
http://www.cplusplus.com/reference/vector/vector/begin/
> Fix possible dereference of begin() iterator when std::vector is empty

- src/util/TunnelIPv6Interface.cpp
It was not causing crach or missing multicast packets since there is a
packet length guard and only one record is sent each time.
> [netif] fix byteorder in mld packet parsing

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit updates the cache table property to include additional
info (now available from NCP) about entries in different states.
---
This PR is related to PRs https://github.com/openthread/openthread/pull/4599 and https://github.com/openthread/openthread/pull/4600. The `toranj` travis tests are expected to fail  and we'd need https://github.com/openthread/openthread/pull/4599 to be merged before this PR.
----
Example of getting cache table with all different types of addresses:
```
[
"fd00:1234::c2:3 -> 0x9c01, Age:0, State:cached, LastTrans:0, ML-EID:fd55:4ce:557:0:262a:543:3e60:cc2d"
"fd00:1234::c2:2 -> 0x9c01, Age:1, State:cached, LastTrans:0, ML-EID:fd55:4ce:557:0:262a:543:3e60:cc2d"
"fd00:1234::c2:1 -> 0x9c01, Age:2, State:cached"
"fd00:1234::c2:0 -> 0x9c01, Age:3, State:cached" …
```
> Update address cache table property

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit fixes the parsing of energy scan response spinel frame by
ensuring to use `unsigned int` as the type of length variable when
unpacking as an spinel data type of  `DATATYPE_DATA_WLEN`.
> Fix parsing of energy scan response spinel frame

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.cpp
- src/wpanctl/tool-cmd-commr.c
- src/wpanctl/tool-cmd-joiner.c
- src/wpantund/NCPConstants.h
- src/wpantund/NCPControlInterface.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit adds support for Joiner Discerner in `wpantund` and `wpanctl`.  The Joiner Discerner enables new a mechanism for Thread commissioning. The traditional Thread commissioning process uses factory assigned EUI-64 of the device to derive the Joiner ID and identify/filter a joiner (through steering data bloom filter). The Joiner Discerner (which is an unsigned value along with a user-specified bit length up to 64 bits) allows users to have more control and do not rely on factory-assigned EUI-64.
For support of Discerner for Joiner operation in `wpantund` two methods are provided: Support for two new wpan properties `Joiner:Discerner:Value` and `Joiner:Discerner:BitLength` are added. To set the Joiner Discerner on device, the bit-length must be set first followed by setting the …
> Add support for Discerner for Joiner/Commissioner

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPInstance.cpp
- src/ncp-dummy/DummyNCPInstance.h
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpanctl/tool-cmd-add-prefix.c
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.h
- third_party/openthread/src/ncp/spinel.h
This PR update the wpantund domain prefix command with new Nd Dns and Domain Prefix flag.
The SPINEL_PROP_THREAD_ON_MESH_NETS property has been extended with new TLV flags field.
> [spinel] update domain prefix spinel property

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit add a  new spinel property to configure Interface Identifier of the Thread Domain Unicast Address.
OT PR: https://github.com/openthread/openthread/pull/6200
> [spinel] add interface identifier of the Thread Domain Unicast Address

- configure.ac
- m4/nl.m4
- script/bootstrap
- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/util/SuperSocket.cpp
- src/util/SuperSocket.h
- src/wpantund/NCPConstants.h
This commit handles the situation when NCP(USB CDC ACM) performs hard reset after receiving SPINEL_CMD_RESET.
When NCP is connected by USB CDC ACM and we reset it, the NCP device is reattached to the host operating system. So far for NCP(USB CDC ACM) pseudo reset has been performing meaning only specific parts of firmware were reset. It is error-prone solution for bare metal device and almost unreachable for devices working under RTOS. But what's most important it does not guarantee the clean init state of the NCP device. It's far easier and better to hard reset NCP and properly handle the USB connection on the host side.
It uses udev library to check if device enumeration has ended.
It works based on symlink to the NCP device created by udev in /dev/serial/by-id/ directory.
> NCP(USB CDC ACM) hard reset support

- INSTALL.md
As mentioned in https://github.com/openthread/wpantund/issues/494, the INSTALL.md is outdated. For now we need to build and install `wpantund` using the latest master branch instead of `full/latest-release`, otherwise the NCP logs won't be forwarded properly.
> [doc] update INSTALL.md to use the latest master instead of full/latest-release

- src/util/netif-mgmt.c
In commit 4e2ef143046a0c89afe6fd66acf5b7a7f35e8356 this header was
added unconditionally. For my system (Yocto with musl) this results in
strlcpy being redefined to __missing_strlcpy in all cases. No matter if
strlcpy is available or not.
Given it is available and the nl.m4 macros detects this, the libstrlcpy.la
helper is not build which results in:
netif-mgmt.c:386: more undefined references to `___missing_strlcpy' follow
Signed-off-by: Stefan Schmidt <stefan.schmidt@huawei.com>
> util/netif-mgmt: only include missing strlcpy header if actually missing

- src/ncp-spinel/SpinelNCPInstance.cpp
Fixed stack-buffer-overflow in metric_len reported at https://github.com/openthread/wpantund/issues/502.
> Fixed stack-buffer-overflow in metric_len

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- doc/wpantund-oss-plan.md
- third_party/openthread/README.md
Replace link to openthread-users Google Group with link to GitHub OpenThread Discussions, clarify issue reporting links, and correct capitalization of 'GitHub'.
> [docs] community discussion change

- .github/workflows/toranj.yml
When CI ran for PR: https://github.com/openthread/wpantund/actions/runs/7385566082
It failed an reported a warning:
I think this may be the root cause. This PR updates the ubuntu environment of CI.
> [toranj] update the CI ubuntu environment

- src/ncp-spinel/SpinelNCPInstance.cpp
- third_party/openthread/src/ncp/spinel.h
Following https://github.com/openthread/openthread/pull/9731, this PR
adds handling of the newly added role 'SPINEL_NET_ROLE_DISABLED'.
> [spinel] handle new spinel net role DISABLED
