- src/connman-plugin/wpan-connman-plugin.c
This commit changes the parsing of dbus message containing the
IPv6MeshLocalPrefix key. The value for this key is currently encoded
as an string (but in earlier build it was encoded as an array).
The new change checks for the type and should work fine with
both encodings.
> wpan-connman-plugin: Change the parsing of the MeshLocalPrefix value

- README.md
> Add window support copy

- src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/util/Makefile.am
- src/util/sec-random.c
- src/util/sec-random.h
- src/wpantund/Makefile.am
- src/wpantund/NCPConstants.h
- src/wpantund/wpantund.cpp
* 22e1e93 ncp_spinel: Allow spinel driver to enter assisting/permit-join mode.
* 0757865 ncp_spinel: Have "Form" generate PANID, XPANID, and Mesh-local Prefix
* 87a90f7 utils: Added secure random number functions
> ncp_spinel: Fixes for "form" command and permit-join mode.

- configure.ac
- src/Makefile.am
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskForm.cpp
- src/scripts/Makefile.am
- src/util/socket-utils.c
- src/wpantund/NCPInstanceBase-NetInterface.cpp
- src/wpantund/NCPInstanceBase.cpp
- src/wpantund/NCPInstanceBase.h
These are miscellaneous changes that were reviewed internally.
> Miscellaneous changes

- third_party/openthread/src/ncp/spinel.h
This syncs `spinel.h` with openthread at commit adba70a3906.
> Spinel.h: Sync spinel header file with openthread

- src/wpantund/wpantund.cpp
> Move free to the proper scope to fix #57

- src/connman-plugin/Makefile.am
> Add missing -module LDFLAG

- src/scripts/wpanretain.sh
This commit changes the `wpanretain.sh` script to use the "RouterId".
> Update the `wpanretain` script to use/retain Router Id

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
Adding new wpantund properties `Thread:RLOC16` and (write-only) `Thread:PreferredRouterID`
> Adding new wpantund properties `Thread:RLOC16` and (write-only) `Thread:PreferredRouterID`

- bootstrap.sh
- etc/autoandr/autoandr
This change fixes some problems that were noticed with the generation of the Android.mk files.
> autoandr: Fix for Android.mk file generation.

- m4/nl.m4
Thanks to Duane Ellis for identifying this condition.
> nl.m4: Address M4 quoting issue

- src/wpanctl/Makefile.am
- src/wpanctl/tool-cmd-mfg.c
- src/wpanctl/tool-cmd-mfg.h
- src/wpanctl/wpanctl-cmds.h
This is needed to execute the manufacturing commands on OpenThread.
> wpanctl: Added `mfg` command.

- src/ncp-spinel/Makefile.am
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/ncp-spinel/SpinelNCPTaskGetMsgBufferCounters.cpp
- src/ncp-spinel/SpinelNCPTaskGetMsgBufferCounters.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.h
This is related to OpenThread https://github.com/openthread/openthread/pull/940 and https://github.com/openthread/openthread/pull/944
Changes have been tested/verified.
> Add support for getting msg buffer counters from NCP

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
The counter-part of this PR in OpenThread is https://github.com/openthread/openthread/pull/966
> Implement support for jam detection feature in Spinel plugin

- src/ncp-spinel/SpinelNCPInstance.cpp
Added tx/rx unicast/broadcast counter support.
> Add support for unicast/broadcast counters

- third_party/openthread/tools/spi-hdlc-adapter/README.md
- third_party/openthread/tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This is from [OpenThread pull request #1066](https://github.com/openthread/openthread/pull/1066).
> spi-hdlc-adapter: Merge changes from OpenThread

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit updates `spinel` files to bring in the new definitions
and changes from OpenThread.
> Update `spinel.c` and `spinel.h` to sync with OpenThread

- src/ncp-spinel/SpinelNCPInstance.cpp
- Adds set/get handlers for the legacy ULA prefix wpan property
`kWPANTUNDProperty_NestLabs_LegacyMeshLocalPrefix`.
- When the legacy ULA property is set, it is retained within
wpantund in the settings map/dictionary and restored on the
NCP upon reset/re-initialization.
> Adding support to set/get legacy ULA prefix and retain it in the settings map

- .gitignore
- bootstrap.sh
- m4/nl.m4
- src/connman-plugin/Makefile.am
- src/connman-plugin/wpan-connman-plugin.c
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
- src/util/Callbacks.h
- src/util/any-to.cpp
- src/util/socket-utils.c
- src/util/socket-utils.h
- src/util/string-utils.c
- src/wpanctl/wpanctl.c
- src/wpantund/IPCServer.h
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPInstanceBase-NetInterface.cpp
- src/wpantund/wpantund.cpp
- third_party/assert-macros/assert-macros.h
This pull requests contains miscellaneous minor fixes and improvements:
* any-to: Allow any_to_string to always work.
* socket-utils: Allow the explicit specification of a TCP socket.
* socket-utils: Use constant macros for setting baud rate.
* Fix various warnings and ignored files.
* connman-plugin: Updates to get the plugin compiling on Android
* connman-plugin: Don't include mcheck.h
> Miscellaneous updates

- src/scripts/wpanretain.sh
This commit modifies the `wpanretain.sh` script recall operation.
When "recall" is issued, the scripts checks if NCP is commissioned
and if the AutoResume feature is enabled on wpantund:
- If NCP is commissioned and AutoResume is enabled, recall is skipped.
- If NCP is commissioned but AutoResume is not enabled, then instead
of recalling the network info from the saved file, a wpantund
"resume" command is issued to restore the saved network from NCP.
- Otherwise, the network info is recalled from the saved file on host.
> `wpanretain.sh`: Check if NCP is commissioned and skip recall

- src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
- src/ncp-spinel/SpinelNCPTaskDeepSleep.cpp
This change avoids a potential churn loop that will occur if the interface is disabled when the NCP doesn't support `CAP_POWER_SAVE`.
In that case, we now simply turn off the stack, interface, and phy.
> ncp-spinel: Require CAP_POWER_SAVE to enter deep sleep via software.

- INSTALL.md
Address the change in brew --prefix vs brew --repository
Address the change in dbus installation path from d-bus to dbus
> update installation instructions for MacOS.

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit updates the spinel files from OpenThread. This syncs
the files with OpenThread at commit 1ece777a8232.
> Update `spinel.h` and `spinel.c` from OpenThread

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
Added support for getting the network partition id
> Partition id

- src/ncp-spinel/SpinelNCPInstance.cpp
Will be super helpful for debugging.
> Add index and the total when child info is added to logs

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpanctl/tool-cmd-begin-net-wake.c
- src/wpanctl/tool-cmd-commissioner.c
- src/wpanctl/wpanctl-utils.c
This PR simply fixes some annoying warnings.
> Fix some compiling warnings

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit includes the changes to the Spinel parser from OpenThread commit 908d7dae, and includes the changes from [PR#2200][2200].
[2200]: https://github.com/openthread/openthread/pull/2200
> spinel: Updates from OpenThread

- src/ncp-spinel/SpinelNCPInstance.cpp
The property `TmfProxy:Stream`, introduced via pull request #160, was not verifying that the size of the input was indeed large enough to satisfy the minimum size requirements. This resulted in out-of-bounds memory reads.
This pull request addresses this issue by performing the appropriate input validation.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3400
> ncp-spinel: Perform input size validation on TMF stream

- src/wpantund/wpantund-fuzz.cpp
Throwing SocketError exceptions is an acceptable error condition.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3392
> wpantund-fuzz: Ignore SocketError exceptions.

- src/util/socket-utils.c
These changes help prevent the fuzer from messing with stuff that it shouldn't, as well as fixing a minor issue discovered during fuzzing.
> socket-utils: Fixes to improve fuzzing performance.

- third_party/openthread/CONTRIBUTING.md
- third_party/openthread/README.google
- third_party/openthread/README.md
- third_party/openthread/tools/spi-hdlc-adapter/README.md
- third_party/openthread/tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This commit updates spi-hdlc-adapter to v0.06.
> openthread: Update files to reflect OpenThread commit a837af7f

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
This property is tied to `SPINEL_PROP_THREAD_ROUTER_ROLE_ENABLED`
spinel property.
> Add new wpantund property "Thread:RouterRole:Enabled"

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit syncs with OpenThread at commit 935d2d07 (#2376).
> Sync spinel.h and spinel.c with OpenThread

- src/wpantund/wpantund-fuzz.cpp
- src/wpantund/wpantund.cpp
[oss-fuzz-3565](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3565) describes an unreproducable (but frequently occuring) global buffer overflow discovered by fuzzing. The immediate cause of the overflow is the failure of `fd_set_merge()` to respect the size boundaries of an `fd_set`, which is limited to accounting to no more than `FD_SETSIZE` file descriptors. That issue was fixed by #263. However, the fact that we are getting anywhere close to the `FD_SETSIZE` file descriptor limit indicates that we may very well be leaking file descriptors.
Pull request #263 added some checks to detect file descriptor leaks, but this pull request introduces better checking that should be able to ferret out the exact sorts of test cases that induce leaking file descriptors.
> Additional diagnostic updates for oss-fuzz-3565

- src/wpanctl/tool-cmd-mfg.c
This commit fixes issues in parsing of input argument for wpanctl `mfg` command. It allows any number of arguments to be provided and ensures that the command string sent to NCP is limited to a maximum
size. Earlier implementation inherently assumed that user would only use commands with at most 3 arguments, and if more arguments were provided it would incorrectly send an uninitialized char buffer as
the command string to NCP which could lead to an NCP crash.
This commit also cleans up the code, removing unused variable declarations  and addressing code style inconsistencies.
> Fix parsing of input arguments in wpanctl mfg command

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/util/time-utils.c
This change addresses a use-of-uninitialized-memory issue discovered by oss-fuzz.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4616
> Fix for usage of uninitialized memory

- Android.mk
- src/ipc-dbus/DBusIPCAPI_v0.cpp
- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/wpantund/NCPMfgInterface_v0.h
- src/wpantund/NCPMfgInterface_v1.h
This PR mainly adds a makefile for android build system. Some warnings are also fixed.
> Add support for Android build system

- Android.mk
This PR eliminate running bootstrap for android build system.
> Eliminate running bootstrap on android

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
Three new properties are introduced:
* TimeSync:ThreadNetworkTime
* TimeSync:Period
* TimeSync:XtalThreshold
Corresponding OpenThread PR: [PR#2618](https://github.com/openthread/openthread/pull/2618)
> support OpenThread time synchronization service

- third_party/openthread/tools/spi-hdlc-adapter/README.md
- third_party/openthread/tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This commit updates spi-hdlc-adapter to v0.07.
> Sync spi-hdlc-adapter to OpenThread commit 60fc0ac0

- src/util/string-utils.h
- src/wpanctl/tool-cmd-dataset.c
- src/wpanctl/tool-cmd-poke.c
- src/wpantund/wpantund.cpp
This addresses some of warnings during build.
> Include "string-utils.h" in tool-cmd-poke and tool-cmd-dataset

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit updates `spinel.h` and `spinel.c` from OpenThread at
commit 5fc1788d375d9.
> Update spinel definition from OpenThread

- third_party/openthread/src/ncp/spinel.h
This commit updates `spinel.h` from OpenThread master branch at
commit f824343f8ca.
> Update spinel header files from OpenThread

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
Add get/set support for wpan property "Thread:ChildTimeout"
> Childtimeout

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
Related PR in OpenThread: https://github.com/openthread/openthread/pull/2939
> Adding support for "Child Supervision" properties in wpantund

- src/ncp-spinel/SpinelNCPInstance.cpp
This commit changes the wpantund state after a reset/resume such that
if the device is a sleepy child, it is starts from `ISOLATED` state
("associated:no-parent") instead of `ASSOCIATING` state. This is
handled from `PROP_NET_STACK_UP` property update by checking if the
device is commissioned AND the thread mode indicates that the device
is sleepy. This commit also ensures that if thread mode is changed
while in either `ISOLATED` or `ASSOCIATING` states, the state is
switched accordingly based on the new mode and whether it is sleepy
or not.
The reason for this change is to ensure wpantund allows host sleep on
a sleepy child with no parent after an NCP reset. Since the
`ASSOCIATING` state is considered a transient state, wpantund blocks
host sleep while in this state. However, host sleep …
> Enter ISOLATED state after resume on a sleepy child

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit syncs spinel files from OT at commit 1ba69deb309.
> Sync spinel files with OpenThread

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.h
> only remove slaac address if no available border routers

- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.h
---
This is follow up on https://github.com/openthread/wpantund/pull/354
Added a `toranj` test-case in https://github.com/openthread/openthread/pull/3111 which covers SLAAC addition/removals.
> Update how the SLAAC addresses are removed

- src/wpantund/NCPInstanceBase-Addresses.cpp
---
credit for the find to oss-fuzz test.
> Fix "use after delete issue"  in on_mesh_prefix_was_removed

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
* rename UDP proxy to UDP forward
* sync spinel.* from OpenThread
> Rename UDP proxy to UDP forward

- configure.ac
- src/ipc-dbus/wpantund.conf.in
Allow change run service with a user other root.
> Allow change user to run wpantund service

- configure.ac
- src/ipc-dbus/wpantund.conf.in
This fixes #389 . I didn't remove `at_console` section to avoid breaking existing projects.
> Add group to allow sending d-bus messages to wpantund

- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This commit update spinel source files from OpenThread at commit
bd2e3ef8f94.
> Update spinel files from OpenThread

- configure.ac
- src/wpanctl/wpanctl.c
This PR switches wpanctl's running to service user if it's not root.
> [wpanctl] switch to service user

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ncp-dummy/DummyNCPInstance.cpp
- src/ncp-dummy/DummyNCPInstance.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpanctl/tool-cmd-add-service.c
- src/wpanctl/tool-cmd-remove-service.c
- src/wpantund/NCPControlInterface.h
- src/wpantund/NCPInstanceBase-Addresses.cpp
- src/wpantund/NCPInstanceBase.cpp
This is purely style/cosmetic change. It removes the extra space
characters from end of lines.
> Remove extra whitespace char at end of lines

- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.h
This is purely style/cosmetic change. It removes the extra space
characters from end of lines.
> Remove extra whitespace char at end of lines (#409)

- src/util/socket-utils.c
Add some further high baud rate options, and some logging.
> Support higher serial baud rates

- src/scripts/wpanretain.sh
Addresses https://github.com/openthread/wpantund/issues/171.
> Remove setting of NodeType in wpanretain script

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This is related to OpenThread PR https://github.com/openthread/openthread/pull/4286
> Adding support for resetting all/subset of NCP counters

- README.md
Addresses issue https://github.com/openthread/wpantund/issues/447
> Update README.md to update link and remove OS X info

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
-----
This is related to openthread/openthread#4440
> Add new properties related to multi radio link feature

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This PR adds CSL-receiver related properties. 
Related PR into OpenThread: https://github.com/openthread/openthread/pull/6135
> Add CSL-related properties

- src/ncp-spinel/SpinelNCPInstance.cpp
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This PR add domain name property.
Related PR into OpenThread: openthread/openthread#6144
> [spinel] add domain name spinel property

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpanctl/Makefile.am
- src/wpanctl/tool-cmd-mlr.c
- src/wpanctl/tool-cmd-mlr.h
- src/wpanctl/wpanctl-cmds.h
- src/wpantund/NCPControlInterface.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
This PR adds Multicast Listener Registration properties.
Related PR into OpenThread: https://github.com/openthread/openthread/pull/6231
> [spinel] Handle Multicast Listener Registration

- src/ipc-dbus/DBusIPCAPI_v1.cpp
- src/ipc-dbus/DBusIPCAPI_v1.h
- src/ipc-dbus/wpan-dbus-v1.h
- src/ncp-dummy/DummyNCPControlInterface.cpp
- src/ncp-dummy/DummyNCPControlInterface.h
- src/ncp-spinel/SpinelNCPControlInterface.cpp
- src/ncp-spinel/SpinelNCPControlInterface.h
- src/ncp-spinel/SpinelNCPInstance.cpp
- src/ncp-spinel/SpinelNCPInstance.h
- src/wpanctl/Makefile.am
- src/wpanctl/tool-cmd-bbr.c
- src/wpanctl/tool-cmd-bbr.h
- src/wpanctl/wpanctl-cmds.h
- src/wpantund/NCPControlInterface.h
- src/wpantund/wpan-properties.h
- third_party/openthread/src/ncp/spinel.c
- third_party/openthread/src/ncp/spinel.h
Related PR into OpenThread: https://github.com/openthread/openthread/pull/6232
> add support for Thread 1.2 Backbone Router properties
